/*
 * MIT License
 *
 * Copyright (c) 2020-2021 11037650 Canada Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_HEAP_IMPL
#error "This is an internal header. Do not include it."
#endif

#include "pottery/pottery_dependencies.h"
#include "pottery/platform/pottery_platform_pragma_push.t.h"



/*
 * Configuration
 */

#ifndef POTTERY_HEAP_PREFIX
    #error "POTTERY_HEAP_PREFIX is not defined."
#endif
#if !POTTERY_LIFECYCLE_CAN_SWAP
    #error "A move or swap expression is required."
#endif
#if !POTTERY_COMPARE_CAN_ORDER
    #error "An ordering comparison expression is required."
#endif

#ifndef POTTERY_HEAP_EXTERN
    #define POTTERY_HEAP_EXTERN /*nothing*/
#endif

#ifndef POTTERY_HEAP_USE_MOVE
    // Decide whether to use move or swap. We need a move expression to move
    // and a value type to define a temporary to move to.
    //
    // We prefer to move rather than swap if possible since this should result
    // in fewer moves. This could in theory be slower than swap if you have
    // some major optimization in swap, like if most of the contents of your
    // objects are identical and don't need to be swapped. If you don't want
    // heap to use move, define HEAP_USE_MOVE to 0, or just don't give it a
    // move expression.
    //
    // TODO: Heap functions using move aren't actually implemented yet.
    // Currently it always swaps.
    // (This will need to be moved elsewhere, probably declarations,
    // since macros are included before the lifecycle template.)
    #if 0 && POTTERY_LIFECYCLE_CAN_MOVE && defined(POTTERY_HEAP_VALUE_TYPE)
        #define POTTERY_HEAP_USE_MOVE 1
    #else
        #define POTTERY_HEAP_USE_MOVE 0
    #endif
#endif

// Context forwarding
#ifdef POTTERY_HEAP_CONTEXT_TYPE
    #define POTTERY_HEAP_CONTEXT_VAL context,
#else
    #define POTTERY_HEAP_CONTEXT_VAL /*nothing*/
#endif



/*
 * Array Access Function Arguments
 */

//!!! AUTOGENERATED:array_access/args.m.h CONFIG:POTTERY_HEAP NAME:pottery_heap
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Defines wrappers for common function arguments for functions that access
    // arrays via the array_access template.

    // ARGS are function arguments
    // VALS are the matching values
    // SOLE means they are the only arguments to the function (so no trailing comma)
    // UNUSED casts them to void to silence unused parameter warnings

    // TODO this is a temporary workaround for container_types not being used
    // everywhere yet.
    #ifdef POTTERY_CONTAINER_TYPES_HAS_CONTEXT
        #if POTTERY_CONTAINER_TYPES_HAS_CONTEXT
            #define POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT 1
        #else
            #define POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT 0
        #endif
    #else
        #ifdef POTTERY_HEAP_CONTEXT_TYPE
            #define POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT 1
        #else
            #define POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT 0
        #endif
    #endif

    #if POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT
        #if !POTTERY_ARRAY_ACCESS_INHERENT_BASE
            #define POTTERY_HEAP_SOLE_ARGS pottery_heap_context_t context, pottery_heap_entry_t base
            #define POTTERY_HEAP_SOLE_VALS context, base
            #define POTTERY_HEAP_ARGS_UNUSED (void)context, (void)base
        #else
            #define POTTERY_HEAP_SOLE_ARGS pottery_heap_context_t context
            #define POTTERY_HEAP_SOLE_VALS context
            #define POTTERY_HEAP_ARGS_UNUSED (void)context
        #endif
    #else
        #if !POTTERY_ARRAY_ACCESS_INHERENT_BASE
            #define POTTERY_HEAP_SOLE_ARGS pottery_heap_entry_t base
            #define POTTERY_HEAP_SOLE_VALS base
            #define POTTERY_HEAP_ARGS_UNUSED (void)base
        #else
            #define POTTERY_HEAP_SOLE_ARGS void
            #define POTTERY_HEAP_SOLE_VALS /*nothing*/
            #define POTTERY_HEAP_ARGS_UNUSED /*nothing*/
        #endif
    #endif
    #if POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT || !POTTERY_ARRAY_ACCESS_INHERENT_BASE
        #define POTTERY_HEAP_ARGS POTTERY_HEAP_SOLE_ARGS ,
        #define POTTERY_HEAP_VALS POTTERY_HEAP_SOLE_VALS ,
    #else
        #define POTTERY_HEAP_ARGS /*nothing*/
        #define POTTERY_HEAP_VALS /*nothing*/
    #endif

    #undef POTTERY_ARRAY_ACCESS_ARGS_HACK_HAS_CONTEXT
//!!! END_AUTOGENERATED



// functions

#define POTTERY_HEAP_NAME(name) POTTERY_CONCAT(POTTERY_HEAP_PREFIX, name)

//!!! AUTOGENERATED:heap/rename.m.h SRC:pottery_heap DEST:POTTERY_HEAP_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames heap identifiers from pottery_heap to POTTERY_HEAP_PREFIX

    // internal
    #define pottery_heap_set_index POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _set_index)
    #define pottery_heap_parent POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _parent)
    #define pottery_heap_child_left POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _child_left)
    #define pottery_heap_child_right POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _child_right)
    #define pottery_heap_sift_down POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _sift_down)
    #define pottery_heap_sift_up POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _sift_up)

    // public sub-range
    #define pottery_heap_build_range POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _build_range)
    #define pottery_heap_expand_bulk_range POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _expand_bulk_range)
    #define pottery_heap_contract_bulk_range POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _contract_bulk_range)
    #define pottery_heap_contract_at_range POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _contract_at_range)
    #define pottery_heap_valid_count_range POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid_count_range)
    #define pottery_heap_valid_range POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid_range)

    // public full-range
    #define pottery_heap_build POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _build)
    #define pottery_heap_expand_bulk POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _expand_bulk)
    #define pottery_heap_contract_bulk POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _contract_bulk)
    #define pottery_heap_contract_at POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _contract_at)
    #define pottery_heap_valid POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid)
    #define pottery_heap_valid_count POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid_count)
//!!! END_AUTOGENERATED



// container types
#ifdef POTTERY_HEAP_EXTERNAL_CONTAINER_TYPES
    #define POTTERY_HEAP_CONTAINER_TYPES_PREFIX POTTERY_HEAP_EXTERNAL_CONTAINER_TYPES
#else
    #define POTTERY_HEAP_CONTAINER_TYPES_PREFIX POTTERY_HEAP_PREFIX
#endif
//!!! AUTOGENERATED:container_types/rename.m.h SRC:pottery_heap DEST:POTTERY_HEAP_CONTAINER_TYPES_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames container_types template identifiers from pottery_heap to POTTERY_HEAP_CONTAINER_TYPES_PREFIX

    #define pottery_heap_value_t POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _value_t)
    #define pottery_heap_ref_t POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _ref_t)
    #define pottery_heap_const_ref_t POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _const_ref_t)
    #define pottery_heap_entry_t POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _entry_t)
    #define pottery_heap_key_t POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _key_t)
    #define pottery_heap_context_t POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _context_t)

    #define pottery_heap_entry_ref POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _entry_ref)
    #define pottery_heap_ref_key POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _ref_key)
    #define pottery_heap_ref_equal POTTERY_CONCAT(POTTERY_HEAP_CONTAINER_TYPES_PREFIX, _ref_equal)
//!!! END_AUTOGENERATED



// lifecycle functions
#ifdef POTTERY_HEAP_EXTERNAL_LIFECYCLE
    #define POTTERY_HEAP_LIFECYCLE_PREFIX POTTERY_HEAP_EXTERNAL_LIFECYCLE
#else
    #define POTTERY_HEAP_LIFECYCLE_PREFIX POTTERY_HEAP_NAME(_lifecycle)
#endif
//!!! AUTOGENERATED:lifecycle/rename.m.h SRC:pottery_heap_lifecycle DEST:POTTERY_HEAP_LIFECYCLE_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames lifecycle identifiers from pottery_heap_lifecycle to POTTERY_HEAP_LIFECYCLE_PREFIX

    #define pottery_heap_lifecycle_init_steal POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _init_steal)
    #define pottery_heap_lifecycle_init_copy POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _init_copy)
    #define pottery_heap_lifecycle_init POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _init)
    #define pottery_heap_lifecycle_destroy POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _destroy)

    #define pottery_heap_lifecycle_swap POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _swap)
    #define pottery_heap_lifecycle_move POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move)
    #define pottery_heap_lifecycle_steal POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _steal)
    #define pottery_heap_lifecycle_copy POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _copy)
    #define pottery_heap_lifecycle_swap_restrict POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _swap_restrict)
    #define pottery_heap_lifecycle_move_restrict POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_restrict)
    #define pottery_heap_lifecycle_steal_restrict POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _steal_restrict)
    #define pottery_heap_lifecycle_copy_restrict POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _copy_restrict)

    #define pottery_heap_lifecycle_destroy_bulk POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _destroy_bulk)
    #define pottery_heap_lifecycle_move_bulk POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk)
    #define pottery_heap_lifecycle_move_bulk_restrict POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_restrict)
    #define pottery_heap_lifecycle_move_bulk_restrict_impl POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_restrict_impl)
    #define pottery_heap_lifecycle_move_bulk_up POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_up)
    #define pottery_heap_lifecycle_move_bulk_up_impl POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_up_impl)
    #define pottery_heap_lifecycle_move_bulk_down POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_down)
    #define pottery_heap_lifecycle_move_bulk_down_impl POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_down_impl)
//!!! END_AUTOGENERATED



// compare functions
#ifdef POTTERY_HEAP_EXTERNAL_COMPARE
    #define POTTERY_HEAP_COMPARE_PREFIX POTTERY_HEAP_EXTERNAL_COMPARE
#else
    #define POTTERY_HEAP_COMPARE_PREFIX POTTERY_HEAP_NAME(_compare)
#endif
//!!! AUTOGENERATED:compare/rename.m.h SRC:pottery_heap_compare DEST:POTTERY_HEAP_COMPARE_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames compare identifiers from pottery_heap_compare to POTTERY_HEAP_COMPARE_PREFIX

    #define pottery_heap_compare_three_way POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _three_way)
    #define pottery_heap_compare_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _equal)
    #define pottery_heap_compare_not_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _not_equal)
    #define pottery_heap_compare_less POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _less)
    #define pottery_heap_compare_less_or_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _less_or_equal)
    #define pottery_heap_compare_greater POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _greater)
    #define pottery_heap_compare_greater_or_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _greater_or_equal)

    #define pottery_heap_compare_min POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _min)
    #define pottery_heap_compare_max POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _max)
    #define pottery_heap_compare_clamp POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _clamp)
    #define pottery_heap_compare_median POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _median)
//!!! END_AUTOGENERATED



// array_access functions
#ifdef POTTERY_HEAP_EXTERNAL_ARRAY_ACCESS
    #define POTTERY_HEAP_ARRAY_ACCESS_PREFIX POTTERY_HEAP_EXTERNAL_ARRAY_ACCESS
#else
    #define POTTERY_HEAP_ARRAY_ACCESS_PREFIX POTTERY_HEAP_NAME(_array_access)
#endif
//!!! AUTOGENERATED:array_access/rename.m.h SRC:pottery_heap_array_access DEST:POTTERY_HEAP_ARRAY_ACCESS_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames array_access identifiers from pottery_heap_array_access to POTTERY_HEAP_ARRAY_ACCESS_PREFIX

    #define pottery_heap_array_access_begin POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _begin)
    #define pottery_heap_array_access_end POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _end)
    #define pottery_heap_array_access_count POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _count)

    #define pottery_heap_array_access_select POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _select)
    #define pottery_heap_array_access_index POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _index)

    #define pottery_heap_array_access_shift POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _shift)
    #define pottery_heap_array_access_offset POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _offset)
    #define pottery_heap_array_access_next POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _next)
    #define pottery_heap_array_access_previous POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _previous)

    #define pottery_heap_array_access_ref POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _ref)
    #define pottery_heap_array_access_equal POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _equal)
    #define pottery_heap_array_access_exists POTTERY_CONCAT(POTTERY_HEAP_ARRAY_ACCESS_PREFIX, _exists)
//!!! END_AUTOGENERATED
