/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_HEAP_IMPL
#error "This is an internal header. Do not include it."
#endif

#include "pottery/pottery_dependencies.h"
#include "pottery/platform/pottery_platform_pragma_push.t.h"



/*
 * Configuration
 */

#ifndef POTTERY_HEAP_PREFIX
    #error "POTTERY_HEAP_PREFIX is not defined."
#endif
#if !POTTERY_LIFECYCLE_CAN_SWAP
    #error "A move or swap expression is required."
#endif
#if !POTTERY_COMPARE_CAN_ORDER
    #error "An ordering comparison expression is required."
#endif

#ifndef POTTERY_HEAP_EXTERN
    #define POTTERY_HEAP_EXTERN /*nothing*/
#endif

#ifndef POTTERY_HEAP_USE_MOVE
    // Decide whether to use move or swap. We need a move expression to move
    // and a value type to define a temporary to move to.
    //
    // We prefer to move rather than swap if possible since this should result
    // in fewer moves. This could in theory be slower than swap if you have
    // some major optimization in swap, like if most of the contents of your
    // objects are identical and don't need to be swapped. If you don't want
    // heap to use move, define HEAP_USE_MOVE to 0, or just don't give it a
    // move expression.
    //
    // TODO: heap functions using move aren't actually implemented yet, it
    // always swaps.
    // TODO this wouldn't work here anyway since macros are usually included
    // before lifecycle functions.
    #if 0 && POTTERY_LIFECYCLE_CAN_MOVE && defined(POTTERY_HEAP_VALUE_TYPE)
        #define POTTERY_HEAP_USE_MOVE 1
    #else
        #define POTTERY_HEAP_USE_MOVE 0
    #endif
#endif

// Context forwarding
#ifdef POTTERY_HEAP_CONTEXT_TYPE
    #define POTTERY_HEAP_CONTEXT_VAL(state) state.context,
#else
    #define POTTERY_HEAP_CONTEXT_VAL(state) /*nothing*/
#endif



// functions

#define POTTERY_HEAP_NAME(name) POTTERY_CONCAT(POTTERY_HEAP_PREFIX, name)

// legacy stuff
#define pottery_access POTTERY_HEAP_NAME(_access)
#define pottery_value_t POTTERY_HEAP_NAME(_legacy_value_t) // TODO remove
#define pottery_context_t POTTERY_HEAP_NAME(_context_t)
#define pottery_state_t POTTERY_HEAP_NAME(_state_t)

//!!! AUTOGENERATED:heap/rename.t SRC:pottery_heap DEST:POTTERY_HEAP_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames heap identifiers from pottery_heap to POTTERY_HEAP_PREFIX

    #define pottery_heap_ref_t POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _ref_t)
    #define pottery_heap_value_t POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _value_t)
    #define pottery_heap_context_t POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _context_t)
    #define pottery_heap_state_t POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _state_t)

    #define pottery_heap POTTERY_HEAP_PREFIX // TODO shouldn't be necessary?
    #define pottery_heap_access POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _access)
    #define pottery_heap_set_index POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _set_index)

    #define pottery_heap_parent POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _parent)
    #define pottery_heap_child_left POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _child_left)
    #define pottery_heap_child_right POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _child_right)
    #define pottery_heap_sift_down POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _sift_down)
    #define pottery_heap_sift_up POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _sift_up)
    #define pottery_heap_build_impl POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _build_impl)
    #define pottery_heap_push_impl POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _push_impl)
    #define pottery_heap_pop_impl POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _pop_impl)
    #define pottery_heap_remove_impl POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _remove_impl)
    #define pottery_heap_valid_count_impl POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid_count_impl)
    #define pottery_heap_build POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _build)
    #define pottery_heap_push POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _push)
    #define pottery_heap_pop POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _pop)
    #define pottery_heap_remove POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _remove)
    #define pottery_heap_valid POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid)
    #define pottery_heap_valid_count POTTERY_CONCAT(POTTERY_HEAP_PREFIX, _valid_count)
//!!! END_AUTOGENERATED



// lifecycle functions
#ifdef POTTERY_HEAP_EXTERNAL_LIFECYCLE
    #define POTTERY_HEAP_LIFECYCLE_PREFIX POTTERY_HEAP_EXTERNAL_LIFECYCLE
#else
    #define POTTERY_HEAP_LIFECYCLE_PREFIX POTTERY_HEAP_NAME(_lifecycle)
#endif
//!!! AUTOGENERATED:lifecycle/rename.t SRC:pottery_heap_lifecycle DEST:POTTERY_HEAP_LIFECYCLE_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames lifecycle identifiers from pottery_heap_lifecycle to POTTERY_HEAP_LIFECYCLE_PREFIX

    // types
    #define pottery_heap_lifecycle_value_t POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _value_t)
    #define pottery_heap_lifecycle_ref_t POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _ref_t)
    #define pottery_heap_lifecycle_const_ref_t POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _const_ref_t)
    #define pottery_heap_lifecycle_context_t POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _context_t)

    // fundamental operations
    #define pottery_heap_lifecycle_init_steal POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _init_steal)
    #define pottery_heap_lifecycle_init_copy POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _init_copy)
    #define pottery_heap_lifecycle_init POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _init)
    #define pottery_heap_lifecycle_destroy POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _destroy)
    #define pottery_heap_lifecycle_swap POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _swap)
    #define pottery_heap_lifecycle_move POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move)
    #define pottery_heap_lifecycle_steal POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _steal)
    #define pottery_heap_lifecycle_copy POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _copy)

    // bulk operations
    #define pottery_heap_lifecycle_destroy_bulk POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _destroy_bulk)
    #define pottery_heap_lifecycle_move_bulk POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk)
    #define pottery_heap_lifecycle_move_bulk_restrict POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_restrict)
    #define pottery_heap_lifecycle_move_bulk_restrict_impl POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_restrict_impl)
    #define pottery_heap_lifecycle_move_bulk_up POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_up)
    #define pottery_heap_lifecycle_move_bulk_up_impl POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_up_impl)
    #define pottery_heap_lifecycle_move_bulk_down POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_down)
    #define pottery_heap_lifecycle_move_bulk_down_impl POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _move_bulk_down_impl)

    // C++
    #define pottery_heap_lifecycle_construct POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _construct)
    #define pottery_heap_lifecycle_assign POTTERY_CONCAT(POTTERY_HEAP_LIFECYCLE_PREFIX, _assign)
//!!! END_AUTOGENERATED



// compare functions
#ifdef POTTERY_HEAP_EXTERNAL_COMPARE
    #define POTTERY_HEAP_COMPARE_PREFIX POTTERY_HEAP_EXTERNAL_COMPARE
#else
    #define POTTERY_HEAP_COMPARE_PREFIX POTTERY_HEAP_NAME(_compare)
#endif
//!!! AUTOGENERATED:compare/rename.t SRC:pottery_heap_compare DEST:POTTERY_HEAP_COMPARE_PREFIX
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames compare identifiers from pottery_heap_compare to POTTERY_HEAP_COMPARE_PREFIX

    #define pottery_heap_compare_ref_t POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _ref_t)
    #define pottery_heap_compare_value_t POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _value_t)
    #define pottery_heap_compare_context_t POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _context_t)

    #define pottery_heap_compare_three_way POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _three_way)
    #define pottery_heap_compare_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _equal)
    #define pottery_heap_compare_not_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _not_equal)
    #define pottery_heap_compare_less POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _less)
    #define pottery_heap_compare_less_or_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _less_or_equal)
    #define pottery_heap_compare_greater POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _greater)
    #define pottery_heap_compare_greater_or_equal POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _greater_or_equal)

    #define pottery_heap_compare_min POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _min)
    #define pottery_heap_compare_max POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _max)
    #define pottery_heap_compare_clamp POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _clamp)
    #define pottery_heap_compare_median POTTERY_CONCAT(POTTERY_HEAP_COMPARE_PREFIX, _median)
//!!! END_AUTOGENERATED
