/*
 * MIT License
 *
 * Copyright (c) 2020-2021 11037650 Canada Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_RED_BLACK_TREE_IMPL
#error "This is an internal header. Do not include it."
#endif

// naming macros
#undef POTTERY_RED_BLACK_TREE_NAME

// configs
#undef POTTERY_RED_BLACK_TREE_LEFT_CHILD
#undef POTTERY_RED_BLACK_TREE_SET_LEFT_CHILD
#undef POTTERY_RED_BLACK_TREE_RIGHT_CHILD
#undef POTTERY_RED_BLACK_TREE_SET_RIGHT_CHILD
#undef POTTERY_RED_BLACK_TREE_PARENT
#undef POTTERY_RED_BLACK_TREE_SET_PARENT
#undef POTTERY_RED_BLACK_TREE_IS_RED
#undef POTTERY_RED_BLACK_TREE_SET_IS_RED

// other macros
#undef POTTERY_RED_BLACK_TREE_HAS_CONTEXT
#undef POTTERY_RED_BLACK_TREE_EXTERN
#undef POTTERY_RBT_CONTEXT_VAL

// public types and functions
#undef pottery_rbt_location_t

// internal accessors
#undef pottery_rbt_left_child
#undef pottery_rbt_set_left_child
#undef pottery_rbt_right_child
#undef pottery_rbt_set_right_child
#undef pottery_rbt_parent
#undef pottery_rbt_set_parent
#undef pottery_rbt_is_red
#undef pottery_rbt_set_is_red
//#undef pottery_rbt_other_child

// other internal functions
#undef pottery_rbt_sanity_check
#undef pottery_rbt_sanity_check_node
#undef pottery_rbt_ref_is_null
#undef pottery_rbt_impl_find_location
#undef pottery_rbt_leftmost_leaf
#undef pottery_rbt_rightmost_leaf




//!!! AUTOGENERATED:container/unrename.m.h PREFIX:pottery_rbt
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_rbt"

    // types
    #undef pottery_rbt_t
    #undef pottery_rbt_entry_t
    #undef pottery_rbt_location_t // currently only used for intrusive maps

    // lifecycle operations
    #undef pottery_rbt_copy
    #undef pottery_rbt_destroy
    #undef pottery_rbt_init
    #undef pottery_rbt_init_copy
    #undef pottery_rbt_init_steal
    #undef pottery_rbt_move
    #undef pottery_rbt_steal
    #undef pottery_rbt_swap

    // entry operations
    #undef pottery_rbt_entry_exists
    #undef pottery_rbt_entry_equal
    #undef pottery_rbt_entry_ref

    // lookup
    #undef pottery_rbt_count
    #undef pottery_rbt_is_empty
    #undef pottery_rbt_at
    #undef pottery_rbt_find
    #undef pottery_rbt_contains_key
    #undef pottery_rbt_first
    #undef pottery_rbt_last
    #undef pottery_rbt_any

    // array access
    #undef pottery_rbt_select
    #undef pottery_rbt_index
    #undef pottery_rbt_shift
    #undef pottery_rbt_offset
    #undef pottery_rbt_begin
    #undef pottery_rbt_end
    #undef pottery_rbt_next
    #undef pottery_rbt_previous

    // misc
    #undef pottery_rbt_capacity
    #undef pottery_rbt_reserve
    #undef pottery_rbt_shrink

    // insert
    #undef pottery_rbt_insert
    #undef pottery_rbt_insert_at
    #undef pottery_rbt_insert_first
    #undef pottery_rbt_insert_last
    #undef pottery_rbt_insert_before
    #undef pottery_rbt_insert_after
    #undef pottery_rbt_insert_bulk
    #undef pottery_rbt_insert_at_bulk
    #undef pottery_rbt_insert_first_bulk
    #undef pottery_rbt_insert_last_bulk
    #undef pottery_rbt_insert_before_bulk
    #undef pottery_rbt_insert_after_bulk

    // emplace
    #undef pottery_rbt_emplace
    #undef pottery_rbt_emplace_at
    #undef pottery_rbt_emplace_key
    #undef pottery_rbt_emplace_first
    #undef pottery_rbt_emplace_last
    #undef pottery_rbt_emplace_before
    #undef pottery_rbt_emplace_after
    #undef pottery_rbt_emplace_bulk
    #undef pottery_rbt_emplace_at_bulk
    #undef pottery_rbt_emplace_first_bulk
    #undef pottery_rbt_emplace_last_bulk
    #undef pottery_rbt_emplace_before_bulk
    #undef pottery_rbt_emplace_after_bulk

    // construct
    #undef pottery_rbt_construct
    #undef pottery_rbt_construct_at
    #undef pottery_rbt_construct_key
    #undef pottery_rbt_construct_first
    #undef pottery_rbt_construct_last
    #undef pottery_rbt_construct_before
    #undef pottery_rbt_construct_after

    // extract
    #undef pottery_rbt_extract
    #undef pottery_rbt_extract_at
    #undef pottery_rbt_extract_key
    #undef pottery_rbt_extract_first
    #undef pottery_rbt_extract_first_bulk
    #undef pottery_rbt_extract_last
    #undef pottery_rbt_extract_last_bulk
    #undef pottery_rbt_extract_and_next
    #undef pottery_rbt_extract_and_previous

    // remove
    #undef pottery_rbt_remove
    #undef pottery_rbt_remove_at
    #undef pottery_rbt_remove_key
    #undef pottery_rbt_remove_first
    #undef pottery_rbt_remove_last
    #undef pottery_rbt_remove_and_next
    #undef pottery_rbt_remove_and_previous
    #undef pottery_rbt_remove_all
    #undef pottery_rbt_remove_bulk
    #undef pottery_rbt_remove_at_bulk
    #undef pottery_rbt_remove_first_bulk
    #undef pottery_rbt_remove_last_bulk
    #undef pottery_rbt_remove_at_bulk
    #undef pottery_rbt_remove_and_next_bulk
    #undef pottery_rbt_remove_and_previous_bulk

    // displace
    #undef pottery_rbt_displace
    #undef pottery_rbt_displace_at
    #undef pottery_rbt_displace_key
    #undef pottery_rbt_displace_first
    #undef pottery_rbt_displace_last
    #undef pottery_rbt_displace_and_next
    #undef pottery_rbt_displace_and_previous
    #undef pottery_rbt_displace_all
    #undef pottery_rbt_displace_bulk
    #undef pottery_rbt_displace_at_bulk
    #undef pottery_rbt_displace_first_bulk
    #undef pottery_rbt_displace_last_bulk
    #undef pottery_rbt_displace_and_next_bulk
    #undef pottery_rbt_displace_and_previous_bulk

    // link
    #undef pottery_rbt_link
    #undef pottery_rbt_link_first
    #undef pottery_rbt_link_last
    #undef pottery_rbt_link_before
    #undef pottery_rbt_link_after

    // unlink
    #undef pottery_rbt_unlink
    #undef pottery_rbt_unlink_at
    #undef pottery_rbt_unlink_key
    #undef pottery_rbt_unlink_first
    #undef pottery_rbt_unlink_last
    #undef pottery_rbt_unlink_and_next
    #undef pottery_rbt_unlink_and_previous
    #undef pottery_rbt_unlink_all

    // special links
    #undef pottery_rbt_replace
    #undef pottery_rbt_find_location
    #undef pottery_rbt_link_location
//!!! END_AUTOGENERATED



// container_types

//!!! AUTOGENERATED:container_types/unconfigure.m.h CONFIG:POTTERY_RED_BLACK_TREE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) container_types configuration on POTTERY_RED_BLACK_TREE

    // types
    #undef POTTERY_RED_BLACK_TREE_VALUE_TYPE
    #undef POTTERY_RED_BLACK_TREE_REF_TYPE
    #undef POTTERY_RED_BLACK_TREE_ENTRY_TYPE
    #undef POTTERY_RED_BLACK_TREE_KEY_TYPE
    #undef POTTERY_RED_BLACK_TREE_CONTEXT_TYPE

    // Conversion and comparison expressions
    #undef POTTERY_RED_BLACK_TREE_ENTRY_REF
    #undef POTTERY_RED_BLACK_TREE_REF_KEY
    #undef POTTERY_RED_BLACK_TREE_REF_EQUAL
//!!! END_AUTOGENERATED

#undef POTTERY_RED_BLACK_TREE_CONTAINER_TYPES_PREFIX
//!!! AUTOGENERATED:container_types/unrename.m.h PREFIX:pottery_rbt
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Unrenames container_types template identifiers from pottery_rbt

    #undef pottery_rbt_value_t
    #undef pottery_rbt_ref_t
    #undef pottery_rbt_const_ref_t
    #undef pottery_rbt_key_t
    #undef pottery_rbt_context_t

    #undef pottery_rbt_ref_key
    #undef pottery_rbt_ref_equal
//!!! END_AUTOGENERATED



// compare

#undef POTTERY_RED_BLACK_TREE_COMPARE_PREFIX
//!!! AUTOGENERATED:compare/unrename.m.h PREFIX:pottery_rbt_compare
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames compare identifiers with prefix "pottery_rbt_compare"

    #undef pottery_rbt_compare_three_way
    #undef pottery_rbt_compare_equal
    #undef pottery_rbt_compare_not_equal
    #undef pottery_rbt_compare_less
    #undef pottery_rbt_compare_less_or_equal
    #undef pottery_rbt_compare_greater
    #undef pottery_rbt_compare_greater_or_equal

    #undef pottery_rbt_compare_min
    #undef pottery_rbt_compare_max
    #undef pottery_rbt_compare_clamp
    #undef pottery_rbt_compare_median
//!!! END_AUTOGENERATED

#undef POTTERY_RED_BLACK_TREE_COMPARE_NAME
//!!! AUTOGENERATED:compare/unconfigure.m.h PREFIX:POTTERY_RED_BLACK_TREE_COMPARE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) compare configuration on POTTERY_RED_BLACK_TREE_COMPARE

    #undef POTTERY_RED_BLACK_TREE_COMPARE_EQUAL
    #undef POTTERY_RED_BLACK_TREE_COMPARE_NOT_EQUAL
    #undef POTTERY_RED_BLACK_TREE_COMPARE_LESS
    #undef POTTERY_RED_BLACK_TREE_COMPARE_LESS_OR_EQUAL
    #undef POTTERY_RED_BLACK_TREE_COMPARE_GREATER
    #undef POTTERY_RED_BLACK_TREE_COMPARE_GREATER_OR_EQUAL
    #undef POTTERY_RED_BLACK_TREE_COMPARE_THREE_WAY
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
