/*
 * MIT License
 *
 * Copyright (c) 2020-2021 11037650 Canada Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_OPEN_HASH_TABLE_IMPL
#error "This is an internal header. Do not include it."
#endif

// user configuration

#undef POTTERY_OPEN_HASH_TABLE_PREFIX
#undef POTTERY_OPEN_HASH_TABLE_EXTERN
#undef POTTERY_OPEN_HASH_TABLE_USE_MOVE
#undef POTTERY_OPEN_HASH_TABLE_EXTERNAL_LIFECYCLE
#undef POTTERY_OPEN_HASH_TABLE_EXTERNAL_COMPARE

#undef POTTERY_OPEN_HASH_TABLE_CONTEXT_TYPE
#undef POTTERY_OPEN_HASH_TABLE_CONTEXT_ARG
#undef POTTERY_OPEN_HASH_TABLE_CONTEXT_VAL
#undef POTTERY_OPEN_HASH_TABLE_CONTEXT_UNUSED

#undef POTTERY_OPEN_HASH_TABLE_ACCESS
#undef POTTERY_OPEN_HASH_TABLE_TOMBSTONES

//!!! AUTOGENERATED:open_hash_table/unconfigure.m.h PREFIX:POTTERY_OPEN_HASH_TABLE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Undefines (forwardable/forwarded) lifecycle configuration on POTTERY_OPEN_HASH_TABLE

    #undef POTTERY_OPEN_HASH_TABLE_VALUE_TYPE
    #undef POTTERY_OPEN_HASH_TABLE_REF_TYPE
    #undef POTTERY_OPEN_HASH_TABLE_KEY_TYPE

    #undef POTTERY_OPEN_HASH_TABLE_KEY_HASH
    #undef POTTERY_OPEN_HASH_TABLE_KEY_EQUAL
    #undef POTTERY_OPEN_HASH_TABLE_REF_KEY

    #undef POTTERY_OPEN_HASH_TABLE_IS_EMPTY
    #undef POTTERY_OPEN_HASH_TABLE_SET_EMPTY
    #undef POTTERY_OPEN_HASH_TABLE_EMPTY_IS_ZERO

    #undef POTTERY_OPEN_HASH_TABLE_IS_TOMBSTONE
    #undef POTTERY_OPEN_HASH_TABLE_SET_TOMBSTONE

    #undef POTTERY_OPEN_HASH_TABLE_IS_VALUE

    #undef POTTERY_OPEN_HASH_TABLE_LINEAR_PROBING
    #undef POTTERY_OPEN_HASH_TABLE_QUADRATIC_PROBING
    #undef POTTERY_OPEN_HASH_TABLE_DOUBLE_HASHING
    #undef POTTERY_OPEN_HASH_TABLE_DOUBLE_HASH_PROBE
//!!! END_AUTOGENERATED



// unrename identifiers

#undef POTTERY_OPEN_HASH_TABLE_NAME

//!!! AUTOGENERATED:open_hash_table/unrename.m.h PREFIX:pottery_oht
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames open_hash_table identifiers with prefix "pottery_oht"

    #undef pottery_oht_emplace
    #undef pottery_oht_insert
    #undef pottery_oht_find
    #undef pottery_oht_displace
    #undef pottery_oht_displace_all
    #undef pottery_oht_remove
    #undef pottery_oht_remove_key
    #undef pottery_oht_remove_all
    #undef pottery_oht_destroy_all
    #undef pottery_oht_contains_key

    #undef pottery_oht_begin
    #undef pottery_oht_end
    #undef pottery_oht_first
    #undef pottery_oht_last
    #undef pottery_oht_next
    #undef pottery_oht_previous

    #undef pottery_oht_key
    #undef pottery_oht_key_hash
    #undef pottery_oht_key_equal
    #undef pottery_oht_double_hash_interval
    #undef pottery_oht_entry_is_tombstone
    #undef pottery_oht_entry_set_tombstone
    #undef pottery_oht_entry_is_empty
    #undef pottery_oht_entry_set_empty
    #undef pottery_oht_entry_is_element
    #undef pottery_oht_entry_in_use
    #undef pottery_oht_entry_exists

    #undef pottery_oht_bucket_for_hash
    #undef pottery_oht_next_probe
    #undef pottery_oht_probe
//!!! END_AUTOGENERATED



// container types

#undef POTTERY_OPEN_HASH_TABLE_CONTAINER_TYPES_PREFIX
//!!! AUTOGENERATED:container_types/unrename.m.h PREFIX:pottery_oht
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Unrenames container_types template identifiers from pottery_oht

    #undef pottery_oht_value_t
    #undef pottery_oht_ref_t
    #undef pottery_oht_const_ref_t
    #undef pottery_oht_entry_t
    #undef pottery_oht_key_t
    #undef pottery_oht_context_t

    #undef pottery_oht_entry_ref
    #undef pottery_oht_ref_key
    #undef pottery_oht_ref_equal
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:container_types/unconfigure.m.h CONFIG:POTTERY_OPEN_HASH_TABLE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) container_types configuration on POTTERY_OPEN_HASH_TABLE

    // types
    #undef POTTERY_OPEN_HASH_TABLE_VALUE_TYPE
    #undef POTTERY_OPEN_HASH_TABLE_REF_TYPE
    #undef POTTERY_OPEN_HASH_TABLE_ENTRY_TYPE
    #undef POTTERY_OPEN_HASH_TABLE_KEY_TYPE
    #undef POTTERY_OPEN_HASH_TABLE_CONTEXT_TYPE

    // Conversion and comparison expressions
    #undef POTTERY_OPEN_HASH_TABLE_ENTRY_REF
    #undef POTTERY_OPEN_HASH_TABLE_REF_KEY
    #undef POTTERY_OPEN_HASH_TABLE_REF_EQUAL
//!!! END_AUTOGENERATED



// lifecycle functions

#undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_PREFIX

//!!! AUTOGENERATED:lifecycle/unrename.m.h PREFIX:pottery_oht_lifecycle
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames lifecycle identifiers with prefix "pottery_oht_lifecycle"

    #undef pottery_oht_lifecycle_init_steal
    #undef pottery_oht_lifecycle_init_copy
    #undef pottery_oht_lifecycle_init
    #undef pottery_oht_lifecycle_destroy
    #undef pottery_oht_lifecycle_swap
    #undef pottery_oht_lifecycle_move
    #undef pottery_oht_lifecycle_steal
    #undef pottery_oht_lifecycle_copy

    #undef pottery_oht_lifecycle_move_bulk
    #undef pottery_oht_lifecycle_move_bulk_restrict
    #undef pottery_oht_lifecycle_move_bulk_restrict_impl
    #undef pottery_oht_lifecycle_move_bulk_up
    #undef pottery_oht_lifecycle_move_bulk_up_impl
    #undef pottery_oht_lifecycle_move_bulk_down
    #undef pottery_oht_lifecycle_move_bulk_down_impl
    #undef pottery_oht_lifecycle_destroy_bulk
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:lifecycle/unconfigure.m.h PREFIX:POTTERY_OPEN_HASH_TABLE_LIFECYCLE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Undefines (forwardable/forwarded) lifecycle configuration on POTTERY_OPEN_HASH_TABLE_LIFECYCLE

    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_DESTROY
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_DESTROY_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_INIT
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_INIT_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_INIT_COPY
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_INIT_COPY_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_INIT_STEAL
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_INIT_STEAL_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_MOVE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_MOVE_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_COPY
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_COPY_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_STEAL
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_STEAL_BY_VALUE
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_SWAP
    #undef POTTERY_OPEN_HASH_TABLE_LIFECYCLE_SWAP_BY_VALUE
//!!! END_AUTOGENERATED



// array_access

//!!! AUTOGENERATED:array_access/unrename.m.h PREFIX:pottery_oht_array_access
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array_access identifiers with prefix "pottery_oht_array_access"

    #undef pottery_oht_array_access_begin
    #undef pottery_oht_array_access_end
    #undef pottery_oht_array_access_count

    #undef pottery_oht_array_access_select
    #undef pottery_oht_array_access_index

    #undef pottery_oht_array_access_shift
    #undef pottery_oht_array_access_offset
    #undef pottery_oht_array_access_next
    #undef pottery_oht_array_access_previous

    #undef pottery_oht_array_access_ref
    #undef pottery_oht_array_access_equal
    #undef pottery_oht_array_access_exists
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:array_access/unconfigure.m.h PREFIX:POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) array_access configuration on POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS

    // absolute addressing configs
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_BEGIN
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_END
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_COUNT

    // required configs for non-standard array access
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_SELECT
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_INDEX

    // required config for non-trivial entries
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_EQUAL

    // optional configs
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_SHIFT
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_OFFSET
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_NEXT
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_PREVIOUS
    #undef POTTERY_OPEN_HASH_TABLE_ARRAY_ACCESS_EXISTS
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
