/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_SHELL_SORT_IMPL
#error "This is an internal header. Do not include it."
#endif

#include "pottery/pottery_dependencies.h"



/*
 * Configuration
 */

#ifndef POTTERY_SHELL_SORT_EXTERN
    #define POTTERY_SHELL_SORT_EXTERN /*nothing*/
#endif

// Context forwarding
#ifdef POTTERY_SHELL_SORT_CONTEXT_TYPE
    #define POTTERY_SHELL_SORT_CONTEXT_VAL(state) state.context,
#else
    #define POTTERY_SHELL_SORT_CONTEXT_VAL(state) /*nothing*/
#endif



/*
 * Renaming
 */

#define POTTERY_SHELL_SORT_NAME(name) \
    POTTERY_CONCAT(POTTERY_SHELL_SORT_PREFIX, name)

#define pottery_shell_sort_ref_t POTTERY_SHELL_SORT_NAME(_ref_t)
#define pottery_shell_sort_value_t POTTERY_SHELL_SORT_NAME(_value_t)
#define pottery_shell_sort_context_t POTTERY_SHELL_SORT_NAME(_context_t)
#define pottery_shell_sort POTTERY_SHELL_SORT_NAME()
#define pottery_shell_sort_insertion_sort POTTERY_SHELL_SORT_NAME(_insertion_sort)
#define pottery_shell_sort_access POTTERY_SHELL_SORT_NAME(_access)
#define pottery_shell_sort_state_t POTTERY_SHELL_SORT_NAME(_state_t)



// lifecycle functions
#ifdef POTTERY_SHELL_SORT_EXTERNAL_LIFECYCLE
    #define POTTERY_SHELL_SORT_LIFECYCLE_NAME(x) POTTERY_CONCAT(POTTERY_SHELL_SORT_EXTERNAL_LIFECYCLE, x)
#else
    #define POTTERY_SHELL_SORT_LIFECYCLE_NAME(x) POTTERY_SHELL_SORT_NAME(POTTERY_CONCAT(_lifecycle, x))
#endif
//!!! AUTOGENERATED:lifecycle/rename.t PREFIX:pottery_shell_sort_lifecycle MACRO:POTTERY_SHELL_SORT_LIFECYCLE_NAME
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Renames lifecycle identifiers with prefix "pottery_shell_sort_lifecycle" using macro POTTERY_SHELL_SORT_LIFECYCLE_NAME()

    // types
    #define pottery_shell_sort_lifecycle_value_t POTTERY_SHELL_SORT_LIFECYCLE_NAME(_value_t)
    #define pottery_shell_sort_lifecycle_ref_t POTTERY_SHELL_SORT_LIFECYCLE_NAME(_ref_t)
    #define pottery_shell_sort_lifecycle_const_ref_t POTTERY_SHELL_SORT_LIFECYCLE_NAME(_const_ref_t)
    #define pottery_shell_sort_lifecycle_context_t POTTERY_SHELL_SORT_LIFECYCLE_NAME(_context_t)

    // fundamental operations
    #define pottery_shell_sort_lifecycle_init_steal POTTERY_SHELL_SORT_LIFECYCLE_NAME(_init_steal)
    #define pottery_shell_sort_lifecycle_init_copy POTTERY_SHELL_SORT_LIFECYCLE_NAME(_init_copy)
    #define pottery_shell_sort_lifecycle_init POTTERY_SHELL_SORT_LIFECYCLE_NAME(_init)
    #define pottery_shell_sort_lifecycle_destroy POTTERY_SHELL_SORT_LIFECYCLE_NAME(_destroy)
    #define pottery_shell_sort_lifecycle_swap POTTERY_SHELL_SORT_LIFECYCLE_NAME(_swap)
    #define pottery_shell_sort_lifecycle_move POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move)
    #define pottery_shell_sort_lifecycle_steal POTTERY_SHELL_SORT_LIFECYCLE_NAME(_steal)
    #define pottery_shell_sort_lifecycle_copy POTTERY_SHELL_SORT_LIFECYCLE_NAME(_copy)

    // bulk operations
    #define pottery_shell_sort_lifecycle_destroy_bulk POTTERY_SHELL_SORT_LIFECYCLE_NAME(_destroy_bulk)
    #define pottery_shell_sort_lifecycle_move_bulk POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk)
    #define pottery_shell_sort_lifecycle_move_bulk_restrict POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk_restrict)
    #define pottery_shell_sort_lifecycle_move_bulk_restrict_impl POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk_restrict_impl)
    #define pottery_shell_sort_lifecycle_move_bulk_up POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk_up)
    #define pottery_shell_sort_lifecycle_move_bulk_up_impl POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk_up_impl)
    #define pottery_shell_sort_lifecycle_move_bulk_down POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk_down)
    #define pottery_shell_sort_lifecycle_move_bulk_down_impl POTTERY_SHELL_SORT_LIFECYCLE_NAME(_move_bulk_down_impl)

    // C++
    #define pottery_shell_sort_lifecycle_construct POTTERY_SHELL_SORT_LIFECYCLE_NAME(_construct)
    #define pottery_shell_sort_lifecycle_assign POTTERY_SHELL_SORT_LIFECYCLE_NAME(_assign)
//!!! END_AUTOGENERATED



// compare functions
#ifdef POTTERY_SHELL_SORT_EXTERNAL_COMPARE
    #define POTTERY_SHELL_SORT_COMPARE_NAME(x) POTTERY_CONCAT(POTTERY_SHELL_SORT_EXTERNAL_COMPARE, x)
#else
    #define POTTERY_SHELL_SORT_COMPARE_NAME(x) POTTERY_SHELL_SORT_NAME(POTTERY_CONCAT(_compare, x))
#endif
//!!! AUTOGENERATED:compare/rename.t PREFIX:pottery_shell_sort_compare MACRO:POTTERY_SHELL_SORT_COMPARE_NAME
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames compare identifiers with prefix "pottery_shell_sort_compare"
    // using macro POTTERY_SHELL_SORT_COMPARE_NAME()
    #define pottery_shell_sort_compare_ref_t POTTERY_SHELL_SORT_COMPARE_NAME(_ref_t)
    #define pottery_shell_sort_compare_value_t POTTERY_SHELL_SORT_COMPARE_NAME(_value_t)
    #define pottery_shell_sort_compare_context_t POTTERY_SHELL_SORT_COMPARE_NAME(_context_t)

    #define pottery_shell_sort_compare_three_way POTTERY_SHELL_SORT_COMPARE_NAME(_three_way)
    #define pottery_shell_sort_compare_equal POTTERY_SHELL_SORT_COMPARE_NAME(_equal)
    #define pottery_shell_sort_compare_not_equal POTTERY_SHELL_SORT_COMPARE_NAME(_not_equal)
    #define pottery_shell_sort_compare_less POTTERY_SHELL_SORT_COMPARE_NAME(_less)
    #define pottery_shell_sort_compare_less_or_equal POTTERY_SHELL_SORT_COMPARE_NAME(_less_or_equal)
    #define pottery_shell_sort_compare_greater POTTERY_SHELL_SORT_COMPARE_NAME(_greater)
    #define pottery_shell_sort_compare_greater_or_equal POTTERY_SHELL_SORT_COMPARE_NAME(_greater_or_equal)

    #define pottery_shell_sort_compare_min POTTERY_SHELL_SORT_COMPARE_NAME(_min)
    #define pottery_shell_sort_compare_max POTTERY_SHELL_SORT_COMPARE_NAME(_max)
    #define pottery_shell_sort_compare_clamp POTTERY_SHELL_SORT_COMPARE_NAME(_clamp)
    #define pottery_shell_sort_compare_median POTTERY_SHELL_SORT_COMPARE_NAME(_median)
//!!! END_AUTOGENERATED
