/*
 * MIT License
 *
 * Copyright (c) 2020-2021 11037650 Canada Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_VECTOR_IMPL
#error "This is an internal header. Do not include it."
#endif



/*
 * Forwarded configurations
 */

//!!! AUTOGENERATED:alloc/unconfigure.m.h PREFIX:POTTERY_VECTOR_ALLOC
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) alloc configuration on POTTERY_VECTOR_ALLOC
    #undef POTTERY_VECTOR_ALLOC_CONTEXT_TYPE

    #undef POTTERY_VECTOR_ALLOC_FREE
    #undef POTTERY_VECTOR_ALLOC_MALLOC
    #undef POTTERY_VECTOR_ALLOC_ZALLOC
    #undef POTTERY_VECTOR_ALLOC_REALLOC
    #undef POTTERY_VECTOR_ALLOC_MALLOC_GOOD_SIZE

    #undef POTTERY_VECTOR_ALLOC_ALIGNED_FREE
    #undef POTTERY_VECTOR_ALLOC_ALIGNED_MALLOC
    #undef POTTERY_VECTOR_ALLOC_ALIGNED_ZALLOC
    #undef POTTERY_VECTOR_ALLOC_ALIGNED_REALLOC
    #undef POTTERY_VECTOR_ALLOC_ALIGNED_MALLOC_GOOD_SIZE
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:lifecycle/unconfigure.m.h PREFIX:POTTERY_VECTOR_LIFECYCLE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Undefines (forwardable/forwarded) lifecycle configuration on POTTERY_VECTOR_LIFECYCLE

    #undef POTTERY_VECTOR_LIFECYCLE_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_DESTROY
    #undef POTTERY_VECTOR_LIFECYCLE_DESTROY_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_INIT
    #undef POTTERY_VECTOR_LIFECYCLE_INIT_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_INIT_COPY
    #undef POTTERY_VECTOR_LIFECYCLE_INIT_COPY_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_INIT_STEAL
    #undef POTTERY_VECTOR_LIFECYCLE_INIT_STEAL_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_MOVE
    #undef POTTERY_VECTOR_LIFECYCLE_MOVE_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_COPY
    #undef POTTERY_VECTOR_LIFECYCLE_COPY_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_STEAL
    #undef POTTERY_VECTOR_LIFECYCLE_STEAL_BY_VALUE
    #undef POTTERY_VECTOR_LIFECYCLE_SWAP
    #undef POTTERY_VECTOR_LIFECYCLE_SWAP_BY_VALUE
//!!! END_AUTOGENERATED



/*
 * Configuration
 */

// internal

#undef POTTERY_VECTOR_PREFIX
#undef POTTERY_VECTOR_MINIMUM_CAPACITY
#undef POTTERY_VECTOR_TYPEDEFS
#undef POTTERY_VECTOR_NAME
#undef POTTERY_VECTOR_VALUE_TYPE

#undef POTTERY_VECTOR_DOUBLE_ENDED
#undef POTTERY_VECTOR_AUTO_SHRINK
#undef POTTERY_VECTOR_INTERNAL_CAPACITY
#undef POTTERY_VECTOR_CXX

#undef POTTERY_VECTOR_EXTERN
#undef POTTERY_VECTOR_CONTEXT_TYPE
#undef POTTERY_VECTOR_CONTEXT_VAL

#undef POTTERY_VECTOR_EXTERNAL_LIFECYCLE
#undef POTTERY_VECTOR_CONTAINER_TYPES_PREFIX


/*
 * Renaming
 */

#undef pottery_vector_data
#undef pottery_vector_const_data
#undef pottery_vector_capacity
#undef pottery_vector_minimum_capacity

#undef pottery_vector_insert_vector
#undef pottery_vector_insert_last_vector
#undef pottery_vector_insert_first_vector

#undef pottery_vector_impl_alloc
#undef pottery_vector_impl_alloc
#undef pottery_vector_impl_free
#undef pottery_vector_impl_clear
#undef pottery_vector_impl_destroy_all
#undef pottery_vector_impl_copy
#undef pottery_vector_impl_reset



// dynamic array functions
//!!! AUTOGENERATED:array/unrename.m.h PREFIX:pottery_vector
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_vector"

    // types
    #undef pottery_vector_t
    #undef pottery_vector_value_t
    #undef pottery_vector_ref_t
    #undef pottery_vector_entry_t
    #undef pottery_vector_context_t

    // fundamental operations
    #undef pottery_vector_copy
    #undef pottery_vector_destroy
    #undef pottery_vector_init
    #undef pottery_vector_init_copy
    #undef pottery_vector_init_steal
    #undef pottery_vector_move
    #undef pottery_vector_steal
    #undef pottery_vector_swap

    // entry operations
    #undef pottery_vector_entry_exists
    #undef pottery_vector_entry_equal
    #undef pottery_vector_entry_value

    // lookup
    #undef pottery_vector_count
    #undef pottery_vector_is_empty
    #undef pottery_vector_at
    #undef pottery_vector_first
    #undef pottery_vector_last
    #undef pottery_vector_any

    // iteration
    #undef pottery_vector_select
    #undef pottery_vector_index
    #undef pottery_vector_begin
    #undef pottery_vector_end
    #undef pottery_vector_next
    #undef pottery_vector_previous

    // misc
    #undef pottery_vector_reserve
    #undef pottery_vector_shrink

    // insert
    #undef pottery_vector_insert_at
    #undef pottery_vector_insert_first
    #undef pottery_vector_insert_last
    #undef pottery_vector_insert_before
    #undef pottery_vector_insert_after
    #undef pottery_vector_insert_at_bulk
    #undef pottery_vector_insert_first_bulk
    #undef pottery_vector_insert_last_bulk
    #undef pottery_vector_insert_before_bulk
    #undef pottery_vector_insert_after_bulk

    // emplace
    #undef pottery_vector_emplace_at
    #undef pottery_vector_emplace_first
    #undef pottery_vector_emplace_last
    #undef pottery_vector_emplace_before
    #undef pottery_vector_emplace_after
    #undef pottery_vector_emplace_at_bulk
    #undef pottery_vector_emplace_first_bulk
    #undef pottery_vector_emplace_last_bulk
    #undef pottery_vector_emplace_before_bulk
    #undef pottery_vector_emplace_after_bulk

    // construct
    #undef pottery_vector_construct_at
    #undef pottery_vector_construct_first
    #undef pottery_vector_construct_last
    #undef pottery_vector_construct_before
    #undef pottery_vector_construct_after

    // extract
    #undef pottery_vector_extract
    #undef pottery_vector_extract_at
    #undef pottery_vector_extract_first
    #undef pottery_vector_extract_last
    #undef pottery_vector_extract_and_next
    #undef pottery_vector_extract_and_previous

    // remove
    #undef pottery_vector_remove
    #undef pottery_vector_remove_at
    #undef pottery_vector_remove_first
    #undef pottery_vector_remove_last
    #undef pottery_vector_remove_and_next
    #undef pottery_vector_remove_and_previous
    #undef pottery_vector_remove_all
    #undef pottery_vector_remove_at_bulk
    #undef pottery_vector_remove_first_bulk
    #undef pottery_vector_remove_last_bulk
    #undef pottery_vector_remove_at_bulk

    // displace
    #undef pottery_vector_displace
    #undef pottery_vector_displace_at
    #undef pottery_vector_displace_first
    #undef pottery_vector_displace_last
    #undef pottery_vector_displace_and_next
    #undef pottery_vector_displace_and_previous
    #undef pottery_vector_displace_all
    #undef pottery_vector_displace_at_bulk
    #undef pottery_vector_displace_first_bulk
    #undef pottery_vector_displace_last_bulk
//!!! END_AUTOGENERATED



// container types

#undef POTTERY_VECTOR_CONTAINER_TYPES_PREFIX
//!!! AUTOGENERATED:container_types/unrename.m.h PREFIX:pottery_vector
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Unrenames container_types template identifiers from pottery_vector

    #undef pottery_vector_value_t
    #undef pottery_vector_ref_t
    #undef pottery_vector_const_ref_t
    #undef pottery_vector_entry_t
    #undef pottery_vector_key_t
    #undef pottery_vector_context_t

    #undef pottery_vector_entry_ref
    #undef pottery_vector_ref_key
    #undef pottery_vector_ref_equal
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:container_types/unconfigure.m.h CONFIG:POTTERY_VECTOR
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) container_types configuration on POTTERY_VECTOR

    // types
    #undef POTTERY_VECTOR_VALUE_TYPE
    #undef POTTERY_VECTOR_REF_TYPE
    #undef POTTERY_VECTOR_ENTRY_TYPE
    #undef POTTERY_VECTOR_KEY_TYPE
    #undef POTTERY_VECTOR_CONTEXT_TYPE

    // Conversion and comparison expressions
    #undef POTTERY_VECTOR_ENTRY_REF
    #undef POTTERY_VECTOR_REF_KEY
    #undef POTTERY_VECTOR_REF_EQUAL
//!!! END_AUTOGENERATED



// lifecycle

#undef POTTERY_VECTOR_LIFECYCLE_PREFIX

//!!! AUTOGENERATED:lifecycle/unrename.m.h PREFIX:pottery_vector_lifecycle
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames lifecycle identifiers with prefix "pottery_vector_lifecycle"

    #undef pottery_vector_lifecycle_init_steal
    #undef pottery_vector_lifecycle_init_copy
    #undef pottery_vector_lifecycle_init
    #undef pottery_vector_lifecycle_destroy
    #undef pottery_vector_lifecycle_swap
    #undef pottery_vector_lifecycle_move
    #undef pottery_vector_lifecycle_steal
    #undef pottery_vector_lifecycle_copy

    #undef pottery_vector_lifecycle_move_bulk
    #undef pottery_vector_lifecycle_move_bulk_restrict
    #undef pottery_vector_lifecycle_move_bulk_restrict_impl
    #undef pottery_vector_lifecycle_move_bulk_up
    #undef pottery_vector_lifecycle_move_bulk_up_impl
    #undef pottery_vector_lifecycle_move_bulk_down
    #undef pottery_vector_lifecycle_move_bulk_down_impl
    #undef pottery_vector_lifecycle_destroy_bulk
//!!! END_AUTOGENERATED



// alloc

#undef POTTERY_VECTOR_ALLOC_PREFIX

//!!! AUTOGENERATED:alloc/unrename.m.h PREFIX:pottery_vector_alloc
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames alloc identifiers with prefix "pottery_vector_alloc"

    #undef pottery_vector_alloc_free
    #undef pottery_vector_alloc_impl_free_ea
    #undef pottery_vector_alloc_impl_free_fa

    #undef pottery_vector_alloc_malloc
    #undef pottery_vector_alloc_impl_malloc_ea
    #undef pottery_vector_alloc_impl_malloc_fa

    #undef pottery_vector_alloc_malloc_zero
    #undef pottery_vector_alloc_impl_malloc_zero_ea
    #undef pottery_vector_alloc_impl_malloc_zero_fa
    #undef pottery_vector_alloc_impl_malloc_zero_fa_wrap

    #undef pottery_vector_alloc_malloc_array_at_least
    #undef pottery_vector_alloc_impl_malloc_array_at_least_ea
    #undef pottery_vector_alloc_impl_malloc_array_at_least_fa

    #undef pottery_vector_alloc_malloc_array
    #undef pottery_vector_alloc_malloc_array_zero
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
