/*
 * MIT License
 *
 * Copyright (c) 2020-2021 11037650 Canada Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_ARRAY_MAP_IMPL
#error "This is an internal header. Do not include it."
#endif

#undef POTTERY_ARRAY_MAP_PREFIX
#undef POTTERY_ARRAY_MAP_KEY_TYPE
#undef POTTERY_ARRAY_MAP_VALUE_TYPE
#undef POTTERY_ARRAY_MAP_REF_KEY
#undef POTTERY_ARRAY_MAP_KEY_EQUAL
#undef POTTERY_ARRAY_MAP_CONTEXT_TYPE

#undef POTTERY_ARRAY_MAP_IMPL
#undef POTTERY_ARRAY_MAP_EXTERN
#undef POTTERY_ARRAY_MAP_NAME

#undef pottery_array_map_t
#undef pottery_array_map_key_t
#undef pottery_array_map_place
#undef pottery_array_map_value_key

#undef POTTERY_ARRAY_MAP_EXTERNAL_CONTAINER_TYPES
#undef POTTERY_ARRAY_MAP_EXTERNAL_LIFECYCLE



// container types

#undef POTTERY_ARRAY_MAP_CONTAINER_TYPES_PREFIX
//!!! AUTOGENERATED:container_types/unrename.m.h PREFIX:pottery_array_map
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Unrenames container_types template identifiers from pottery_array_map

    #undef pottery_array_map_value_t
    #undef pottery_array_map_ref_t
    #undef pottery_array_map_const_ref_t
    #undef pottery_array_map_key_t
    #undef pottery_array_map_context_t

    #undef pottery_array_map_ref_key
    #undef pottery_array_map_ref_equal
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:container_types/unconfigure.m.h CONFIG:POTTERY_ARRAY_MAP
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) container_types configuration on POTTERY_ARRAY_MAP

    // types
    #undef POTTERY_ARRAY_MAP_VALUE_TYPE
    #undef POTTERY_ARRAY_MAP_REF_TYPE
    #undef POTTERY_ARRAY_MAP_ENTRY_TYPE
    #undef POTTERY_ARRAY_MAP_KEY_TYPE
    #undef POTTERY_ARRAY_MAP_CONTEXT_TYPE

    // Conversion and comparison expressions
    #undef POTTERY_ARRAY_MAP_ENTRY_REF
    #undef POTTERY_ARRAY_MAP_REF_KEY
    #undef POTTERY_ARRAY_MAP_REF_EQUAL
//!!! END_AUTOGENERATED



// compare

#undef POTTERY_ARRAY_MAP_COMPARE_PREFIX
//!!! AUTOGENERATED:compare/unrename.m.h PREFIX:pottery_array_map_compare
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames compare identifiers with prefix "pottery_array_map_compare"

    #undef pottery_array_map_compare_three_way
    #undef pottery_array_map_compare_equal
    #undef pottery_array_map_compare_not_equal
    #undef pottery_array_map_compare_less
    #undef pottery_array_map_compare_less_or_equal
    #undef pottery_array_map_compare_greater
    #undef pottery_array_map_compare_greater_or_equal

    #undef pottery_array_map_compare_min
    #undef pottery_array_map_compare_max
    #undef pottery_array_map_compare_clamp
    #undef pottery_array_map_compare_median
//!!! END_AUTOGENERATED

#undef POTTERY_ARRAY_MAP_COMPARE_NAME
//!!! AUTOGENERATED:compare/unconfigure.m.h PREFIX:POTTERY_ARRAY_MAP_COMPARE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) compare configuration on POTTERY_ARRAY_MAP_COMPARE

    #undef POTTERY_ARRAY_MAP_COMPARE_EQUAL
    #undef POTTERY_ARRAY_MAP_COMPARE_NOT_EQUAL
    #undef POTTERY_ARRAY_MAP_COMPARE_LESS
    #undef POTTERY_ARRAY_MAP_COMPARE_LESS_OR_EQUAL
    #undef POTTERY_ARRAY_MAP_COMPARE_GREATER
    #undef POTTERY_ARRAY_MAP_COMPARE_GREATER_OR_EQUAL
    #undef POTTERY_ARRAY_MAP_COMPARE_THREE_WAY
//!!! END_AUTOGENERATED



// lifecycle functions

#undef POTTERY_ARRAY_MAP_LIFECYCLE_PREFIX
//!!! AUTOGENERATED:lifecycle/unrename.m.h PREFIX:pottery_array_map_lifecycle
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames lifecycle identifiers with prefix "pottery_array_map_lifecycle"

    #undef pottery_array_map_lifecycle_init_steal
    #undef pottery_array_map_lifecycle_init_copy
    #undef pottery_array_map_lifecycle_init
    #undef pottery_array_map_lifecycle_destroy
    #undef pottery_array_map_lifecycle_swap
    #undef pottery_array_map_lifecycle_move
    #undef pottery_array_map_lifecycle_steal
    #undef pottery_array_map_lifecycle_copy

    #undef pottery_array_map_lifecycle_move_bulk
    #undef pottery_array_map_lifecycle_move_bulk_restrict
    #undef pottery_array_map_lifecycle_move_bulk_restrict_impl
    #undef pottery_array_map_lifecycle_move_bulk_up
    #undef pottery_array_map_lifecycle_move_bulk_up_impl
    #undef pottery_array_map_lifecycle_move_bulk_down
    #undef pottery_array_map_lifecycle_move_bulk_down_impl
    #undef pottery_array_map_lifecycle_destroy_bulk
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:lifecycle/unconfigure.m.h PREFIX:POTTERY_ARRAY_MAP_LIFECYCLE
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Undefines (forwardable/forwarded) lifecycle configuration on POTTERY_ARRAY_MAP_LIFECYCLE

    #undef POTTERY_ARRAY_MAP_LIFECYCLE_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_DESTROY
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_DESTROY_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_INIT
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_INIT_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_INIT_COPY
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_INIT_COPY_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_INIT_STEAL
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_INIT_STEAL_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_MOVE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_MOVE_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_COPY
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_COPY_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_STEAL
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_STEAL_BY_VALUE
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_SWAP
    #undef POTTERY_ARRAY_MAP_LIFECYCLE_SWAP_BY_VALUE
//!!! END_AUTOGENERATED



//!!! AUTOGENERATED:container/unrename.m.h PREFIX:pottery_array_map
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_array_map"

    // types
    #undef pottery_array_map_t
    #undef pottery_array_map_value_t
    #undef pottery_array_map_ref_t
    #undef pottery_array_map_entry_t
    #undef pottery_array_map_context_t

    // lifecycle operations
    #undef pottery_array_map_copy
    #undef pottery_array_map_destroy
    #undef pottery_array_map_init
    #undef pottery_array_map_init_copy
    #undef pottery_array_map_init_steal
    #undef pottery_array_map_move
    #undef pottery_array_map_steal
    #undef pottery_array_map_swap

    // entry operations
    #undef pottery_array_map_entry_exists
    #undef pottery_array_map_entry_equal
    #undef pottery_array_map_entry_value

    // lookup
    #undef pottery_array_map_count
    #undef pottery_array_map_is_empty
    #undef pottery_array_map_at
    #undef pottery_array_map_find
    #undef pottery_array_map_contains_key
    #undef pottery_array_map_first
    #undef pottery_array_map_last
    #undef pottery_array_map_any

    // array access
    #undef pottery_array_map_select
    #undef pottery_array_map_index
    #undef pottery_array_map_shift
    #undef pottery_array_map_offset
    #undef pottery_array_map_begin
    #undef pottery_array_map_end
    #undef pottery_array_map_next
    #undef pottery_array_map_previous

    // misc
    #undef pottery_array_map_capacity
    #undef pottery_array_map_reserve
    #undef pottery_array_map_shrink

    // insert
    #undef pottery_array_map_insert
    #undef pottery_array_map_insert_at
    #undef pottery_array_map_insert_first
    #undef pottery_array_map_insert_last
    #undef pottery_array_map_insert_before
    #undef pottery_array_map_insert_after
    #undef pottery_array_map_insert_bulk
    #undef pottery_array_map_insert_at_bulk
    #undef pottery_array_map_insert_first_bulk
    #undef pottery_array_map_insert_last_bulk
    #undef pottery_array_map_insert_before_bulk
    #undef pottery_array_map_insert_after_bulk

    // emplace
    #undef pottery_array_map_emplace
    #undef pottery_array_map_emplace_at
    #undef pottery_array_map_emplace_key
    #undef pottery_array_map_emplace_first
    #undef pottery_array_map_emplace_last
    #undef pottery_array_map_emplace_before
    #undef pottery_array_map_emplace_after
    #undef pottery_array_map_emplace_bulk
    #undef pottery_array_map_emplace_at_bulk
    #undef pottery_array_map_emplace_first_bulk
    #undef pottery_array_map_emplace_last_bulk
    #undef pottery_array_map_emplace_before_bulk
    #undef pottery_array_map_emplace_after_bulk

    // construct
    #undef pottery_array_map_construct
    #undef pottery_array_map_construct_at
    #undef pottery_array_map_construct_key
    #undef pottery_array_map_construct_first
    #undef pottery_array_map_construct_last
    #undef pottery_array_map_construct_before
    #undef pottery_array_map_construct_after

    // extract
    #undef pottery_array_map_extract
    #undef pottery_array_map_extract_at
    #undef pottery_array_map_extract_key
    #undef pottery_array_map_extract_first
    #undef pottery_array_map_extract_first_bulk
    #undef pottery_array_map_extract_last
    #undef pottery_array_map_extract_last_bulk
    #undef pottery_array_map_extract_and_next
    #undef pottery_array_map_extract_and_previous

    // remove
    #undef pottery_array_map_remove
    #undef pottery_array_map_remove_at
    #undef pottery_array_map_remove_key
    #undef pottery_array_map_remove_first
    #undef pottery_array_map_remove_last
    #undef pottery_array_map_remove_and_next
    #undef pottery_array_map_remove_and_previous
    #undef pottery_array_map_remove_all
    #undef pottery_array_map_remove_bulk
    #undef pottery_array_map_remove_at_bulk
    #undef pottery_array_map_remove_first_bulk
    #undef pottery_array_map_remove_last_bulk
    #undef pottery_array_map_remove_at_bulk
    #undef pottery_array_map_remove_and_next_bulk
    #undef pottery_array_map_remove_and_previous_bulk

    // displace
    #undef pottery_array_map_displace
    #undef pottery_array_map_displace_at
    #undef pottery_array_map_displace_key
    #undef pottery_array_map_displace_first
    #undef pottery_array_map_displace_last
    #undef pottery_array_map_displace_and_next
    #undef pottery_array_map_displace_and_previous
    #undef pottery_array_map_displace_all
    #undef pottery_array_map_displace_bulk
    #undef pottery_array_map_displace_at_bulk
    #undef pottery_array_map_displace_first_bulk
    #undef pottery_array_map_displace_last_bulk
    #undef pottery_array_map_displace_and_next_bulk
    #undef pottery_array_map_displace_and_previous_bulk
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:container/unrename.m.h PREFIX:pottery_array_map_vector
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_array_map_vector"

    // types
    #undef pottery_array_map_vector_t
    #undef pottery_array_map_vector_value_t
    #undef pottery_array_map_vector_ref_t
    #undef pottery_array_map_vector_entry_t
    #undef pottery_array_map_vector_context_t

    // lifecycle operations
    #undef pottery_array_map_vector_copy
    #undef pottery_array_map_vector_destroy
    #undef pottery_array_map_vector_init
    #undef pottery_array_map_vector_init_copy
    #undef pottery_array_map_vector_init_steal
    #undef pottery_array_map_vector_move
    #undef pottery_array_map_vector_steal
    #undef pottery_array_map_vector_swap

    // entry operations
    #undef pottery_array_map_vector_entry_exists
    #undef pottery_array_map_vector_entry_equal
    #undef pottery_array_map_vector_entry_value

    // lookup
    #undef pottery_array_map_vector_count
    #undef pottery_array_map_vector_is_empty
    #undef pottery_array_map_vector_at
    #undef pottery_array_map_vector_find
    #undef pottery_array_map_vector_contains_key
    #undef pottery_array_map_vector_first
    #undef pottery_array_map_vector_last
    #undef pottery_array_map_vector_any

    // array access
    #undef pottery_array_map_vector_select
    #undef pottery_array_map_vector_index
    #undef pottery_array_map_vector_shift
    #undef pottery_array_map_vector_offset
    #undef pottery_array_map_vector_begin
    #undef pottery_array_map_vector_end
    #undef pottery_array_map_vector_next
    #undef pottery_array_map_vector_previous

    // misc
    #undef pottery_array_map_vector_capacity
    #undef pottery_array_map_vector_reserve
    #undef pottery_array_map_vector_shrink

    // insert
    #undef pottery_array_map_vector_insert
    #undef pottery_array_map_vector_insert_at
    #undef pottery_array_map_vector_insert_first
    #undef pottery_array_map_vector_insert_last
    #undef pottery_array_map_vector_insert_before
    #undef pottery_array_map_vector_insert_after
    #undef pottery_array_map_vector_insert_bulk
    #undef pottery_array_map_vector_insert_at_bulk
    #undef pottery_array_map_vector_insert_first_bulk
    #undef pottery_array_map_vector_insert_last_bulk
    #undef pottery_array_map_vector_insert_before_bulk
    #undef pottery_array_map_vector_insert_after_bulk

    // emplace
    #undef pottery_array_map_vector_emplace
    #undef pottery_array_map_vector_emplace_at
    #undef pottery_array_map_vector_emplace_key
    #undef pottery_array_map_vector_emplace_first
    #undef pottery_array_map_vector_emplace_last
    #undef pottery_array_map_vector_emplace_before
    #undef pottery_array_map_vector_emplace_after
    #undef pottery_array_map_vector_emplace_bulk
    #undef pottery_array_map_vector_emplace_at_bulk
    #undef pottery_array_map_vector_emplace_first_bulk
    #undef pottery_array_map_vector_emplace_last_bulk
    #undef pottery_array_map_vector_emplace_before_bulk
    #undef pottery_array_map_vector_emplace_after_bulk

    // construct
    #undef pottery_array_map_vector_construct
    #undef pottery_array_map_vector_construct_at
    #undef pottery_array_map_vector_construct_key
    #undef pottery_array_map_vector_construct_first
    #undef pottery_array_map_vector_construct_last
    #undef pottery_array_map_vector_construct_before
    #undef pottery_array_map_vector_construct_after

    // extract
    #undef pottery_array_map_vector_extract
    #undef pottery_array_map_vector_extract_at
    #undef pottery_array_map_vector_extract_key
    #undef pottery_array_map_vector_extract_first
    #undef pottery_array_map_vector_extract_first_bulk
    #undef pottery_array_map_vector_extract_last
    #undef pottery_array_map_vector_extract_last_bulk
    #undef pottery_array_map_vector_extract_and_next
    #undef pottery_array_map_vector_extract_and_previous

    // remove
    #undef pottery_array_map_vector_remove
    #undef pottery_array_map_vector_remove_at
    #undef pottery_array_map_vector_remove_key
    #undef pottery_array_map_vector_remove_first
    #undef pottery_array_map_vector_remove_last
    #undef pottery_array_map_vector_remove_and_next
    #undef pottery_array_map_vector_remove_and_previous
    #undef pottery_array_map_vector_remove_all
    #undef pottery_array_map_vector_remove_bulk
    #undef pottery_array_map_vector_remove_at_bulk
    #undef pottery_array_map_vector_remove_first_bulk
    #undef pottery_array_map_vector_remove_last_bulk
    #undef pottery_array_map_vector_remove_at_bulk
    #undef pottery_array_map_vector_remove_and_next_bulk
    #undef pottery_array_map_vector_remove_and_previous_bulk

    // displace
    #undef pottery_array_map_vector_displace
    #undef pottery_array_map_vector_displace_at
    #undef pottery_array_map_vector_displace_key
    #undef pottery_array_map_vector_displace_first
    #undef pottery_array_map_vector_displace_last
    #undef pottery_array_map_vector_displace_and_next
    #undef pottery_array_map_vector_displace_and_previous
    #undef pottery_array_map_vector_displace_all
    #undef pottery_array_map_vector_displace_bulk
    #undef pottery_array_map_vector_displace_at_bulk
    #undef pottery_array_map_vector_displace_first_bulk
    #undef pottery_array_map_vector_displace_last_bulk
    #undef pottery_array_map_vector_displace_and_next_bulk
    #undef pottery_array_map_vector_displace_and_previous_bulk
//!!! END_AUTOGENERATED
