/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_INSERTION_SORT_IMPL
#error "This is an internal header. Do not include it."
#endif

#include "pottery/pottery_dependencies.h"



/*
 * Configuration
 */

#ifndef POTTERY_INSERTION_SORT_PREFIX
    #error "POTTERY_INSERTION_SORT_PREFIX is not defined."
#endif

#if !POTTERY_LIFECYCLE_CAN_MOVE && !POTTERY_LIFECYCLE_CAN_SWAP
    #error "A move or swap expression is required."
#endif
#if !POTTERY_COMPARE_CAN_ORDER
    #error "An ordering comparison expression is required."
#endif

#ifndef POTTERY_INSERTION_SORT_EXTERN
    #define POTTERY_INSERTION_SORT_EXTERN /*nothing*/
#endif

#ifndef POTTERY_INSERTION_SORT_USE_MOVE
    // Decide whether to use move or swap. We need a move expression to move
    // and a value type to define a temporary to move to.
    //
    // We prefer to move rather than swap if possible since this should result
    // in fewer moves. This could in theory be slower than swap if you have
    // some major optimization in swap, like if most of the contents of your
    // objects are identical and don't need to be swapped. If you don't want
    // insertion_sort to use move, define POTTERY_INSERTION_SORT_USE_MOVE to 0,
    // or just don't give it a move expression.
    #if POTTERY_LIFECYCLE_CAN_MOVE && defined(POTTERY_INSERTION_SORT_VALUE_TYPE)
        #define POTTERY_INSERTION_SORT_USE_MOVE 1
    #else
        #define POTTERY_INSERTION_SORT_USE_MOVE 0
    #endif
#endif

// See if we should accept a separate lifecycle context parameter
#ifndef POTTERY_INSERTION_SORT_CONTEXT_IS_LIFECYCLE_CONTEXT
    #define POTTERY_INSERTION_SORT_CONTEXT_IS_LIFECYCLE_CONTEXT 0
#endif
#if defined(POTTERY_INSERTION_SORT_LIFECYCLE_CONTEXT_TYPE) && !POTTERY_INSERTION_SORT_CONTEXT_IS_LIFECYCLE_CONTEXT
    #define POTTERY_INSERTION_SORT_SEPARATE_LIFECYCLE_CONTEXT 1
#else
    #define POTTERY_INSERTION_SORT_SEPARATE_LIFECYCLE_CONTEXT 0
#endif

// See if we should accept a separate compare context parameter
#ifndef POTTERY_INSERTION_SORT_CONTEXT_IS_COMPARE_CONTEXT
    #define POTTERY_INSERTION_SORT_CONTEXT_IS_COMPARE_CONTEXT 0
#endif
#if defined(POTTERY_INSERTION_SORT_COMPARE_CONTEXT_TYPE) && !POTTERY_INSERTION_SORT_CONTEXT_IS_COMPARE_CONTEXT
    #define POTTERY_INSERTION_SORT_SEPARATE_COMPARE_CONTEXT 1
#else
    #define POTTERY_INSERTION_SORT_SEPARATE_COMPARE_CONTEXT 0
#endif



/*
 * Renaming
 */

#define POTTERY_INSERTION_SORT_NAME(name) \
    POTTERY_CONCAT(POTTERY_INSERTION_SORT_PREFIX, name)

//!!! AUTOGENERATED:insertion_sort/rename.t PREFIX:pottery_insertion_sort MACRO:POTTERY_INSERTION_SORT_NAME
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames insertion_sort identifiers with prefix "pottery_insertion_sort"
    // using macro POTTERY_INSERTION_SORT_NAME()
    #define pottery_insertion_sort_ref_t POTTERY_INSERTION_SORT_NAME(_ref_t)
    #define pottery_insertion_sort_value_t POTTERY_INSERTION_SORT_NAME(_value_t)
    #define pottery_insertion_sort_context_t POTTERY_INSERTION_SORT_NAME(_context_t)
    #define pottery_insertion_sort_state_t POTTERY_INSERTION_SORT_NAME(_state_t)

    #define pottery_insertion_sort POTTERY_INSERTION_SORT_NAME()
    #define pottery_insertion_sort_access POTTERY_INSERTION_SORT_NAME(_access)
    #define pottery_insertion_sort_move POTTERY_INSERTION_SORT_NAME(_move)
    #define pottery_insertion_sort_swap POTTERY_INSERTION_SORT_NAME(_swap)
    #define pottery_insertion_sort_before POTTERY_INSERTION_SORT_NAME(_before)
    #define pottery_insertion_sort_by_move POTTERY_INSERTION_SORT_NAME(_by_move)
    #define pottery_insertion_sort_by_swap POTTERY_INSERTION_SORT_NAME(_by_swap)
//!!! END_AUTOGENERATED



// lifecycle functions
#ifdef POTTERY_INSERTION_SORT_EXTERNAL_LIFECYCLE
    #define POTTERY_INSERTION_SORT_LIFECYCLE_NAME(x) POTTERY_CONCAT(POTTERY_INSERTION_SORT_EXTERNAL_LIFECYCLE, x)
#else
    #define POTTERY_INSERTION_SORT_LIFECYCLE_NAME(x) POTTERY_INSERTION_SORT_NAME(POTTERY_CONCAT(_lifecycle, x))
#endif
//!!! AUTOGENERATED:lifecycle/rename.t PREFIX:pottery_insertion_sort_lifecycle MACRO:POTTERY_INSERTION_SORT_LIFECYCLE_NAME
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Renames lifecycle identifiers with prefix "pottery_insertion_sort_lifecycle" using macro POTTERY_INSERTION_SORT_LIFECYCLE_NAME()

    // types
    #define pottery_insertion_sort_lifecycle_value_t POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_value_t)
    #define pottery_insertion_sort_lifecycle_ref_t POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_ref_t)
    #define pottery_insertion_sort_lifecycle_const_ref_t POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_const_ref_t)
    #define pottery_insertion_sort_lifecycle_context_t POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_context_t)

    // fundamental operations
    #define pottery_insertion_sort_lifecycle_init_steal POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_init_steal)
    #define pottery_insertion_sort_lifecycle_init_copy POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_init_copy)
    #define pottery_insertion_sort_lifecycle_init POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_init)
    #define pottery_insertion_sort_lifecycle_destroy POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_destroy)
    #define pottery_insertion_sort_lifecycle_swap POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_swap)
    #define pottery_insertion_sort_lifecycle_move POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move)
    #define pottery_insertion_sort_lifecycle_steal POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_steal)
    #define pottery_insertion_sort_lifecycle_copy POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_copy)

    // bulk operations
    #define pottery_insertion_sort_lifecycle_destroy_bulk POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_destroy_bulk)
    #define pottery_insertion_sort_lifecycle_move_bulk POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk)
    #define pottery_insertion_sort_lifecycle_move_bulk_restrict POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk_restrict)
    #define pottery_insertion_sort_lifecycle_move_bulk_restrict_impl POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk_restrict_impl)
    #define pottery_insertion_sort_lifecycle_move_bulk_up POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk_up)
    #define pottery_insertion_sort_lifecycle_move_bulk_up_impl POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk_up_impl)
    #define pottery_insertion_sort_lifecycle_move_bulk_down POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk_down)
    #define pottery_insertion_sort_lifecycle_move_bulk_down_impl POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_move_bulk_down_impl)

    // C++
    #define pottery_insertion_sort_lifecycle_construct POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_construct)
    #define pottery_insertion_sort_lifecycle_assign POTTERY_INSERTION_SORT_LIFECYCLE_NAME(_assign)
//!!! END_AUTOGENERATED



// compare functions
#ifdef POTTERY_INSERTION_SORT_EXTERNAL_COMPARE
    #define POTTERY_INSERTION_SORT_COMPARE_NAME(x) POTTERY_CONCAT(POTTERY_INSERTION_SORT_EXTERNAL_COMPARE, x)
#else
    #define POTTERY_INSERTION_SORT_COMPARE_NAME(x) POTTERY_INSERTION_SORT_NAME(POTTERY_CONCAT(_compare, x))
#endif
//!!! AUTOGENERATED:compare/rename.t PREFIX:pottery_insertion_sort_compare MACRO:POTTERY_INSERTION_SORT_COMPARE_NAME
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames compare identifiers with prefix "pottery_insertion_sort_compare"
    // using macro POTTERY_INSERTION_SORT_COMPARE_NAME()
    #define pottery_insertion_sort_compare_ref_t POTTERY_INSERTION_SORT_COMPARE_NAME(_ref_t)
    #define pottery_insertion_sort_compare_value_t POTTERY_INSERTION_SORT_COMPARE_NAME(_value_t)
    #define pottery_insertion_sort_compare_context_t POTTERY_INSERTION_SORT_COMPARE_NAME(_context_t)

    #define pottery_insertion_sort_compare_three_way POTTERY_INSERTION_SORT_COMPARE_NAME(_three_way)
    #define pottery_insertion_sort_compare_equal POTTERY_INSERTION_SORT_COMPARE_NAME(_equal)
    #define pottery_insertion_sort_compare_not_equal POTTERY_INSERTION_SORT_COMPARE_NAME(_not_equal)
    #define pottery_insertion_sort_compare_less POTTERY_INSERTION_SORT_COMPARE_NAME(_less)
    #define pottery_insertion_sort_compare_less_or_equal POTTERY_INSERTION_SORT_COMPARE_NAME(_less_or_equal)
    #define pottery_insertion_sort_compare_greater POTTERY_INSERTION_SORT_COMPARE_NAME(_greater)
    #define pottery_insertion_sort_compare_greater_or_equal POTTERY_INSERTION_SORT_COMPARE_NAME(_greater_or_equal)

    #define pottery_insertion_sort_compare_min POTTERY_INSERTION_SORT_COMPARE_NAME(_min)
    #define pottery_insertion_sort_compare_max POTTERY_INSERTION_SORT_COMPARE_NAME(_max)
    #define pottery_insertion_sort_compare_clamp POTTERY_INSERTION_SORT_COMPARE_NAME(_clamp)
    #define pottery_insertion_sort_compare_median POTTERY_INSERTION_SORT_COMPARE_NAME(_median)
//!!! END_AUTOGENERATED
