/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_HEAP_SORT_IMPL
#error "This is an internal header. Do not include it."
#endif

#include "pottery/pottery_dependencies.h"



/*
 * Configuration
 */

#ifndef POTTERY_HEAP_SORT_EXTERN
    #define POTTERY_HEAP_SORT_EXTERN /*nothing*/
#endif



/*
 * Renaming
 */

#define POTTERY_HEAP_SORT_NAME(name) POTTERY_CONCAT(POTTERY_HEAP_SORT_PREFIX, name)

#define pottery_heap_sort_ref_t POTTERY_HEAP_SORT_NAME(_ref_t)
#define pottery_heap_sort_value_t POTTERY_HEAP_SORT_NAME(_value_t)
#define pottery_heap_sort_context_t POTTERY_HEAP_SORT_NAME(_context_t)
#define pottery_heap_sort_lifecycle_context_t POTTERY_HEAP_SORT_NAME(_lifecycle_context_t)
#define pottery_heap_sort_compare_context_t POTTERY_HEAP_SORT_NAME(_compare_context_t)
#define pottery_heap_sort POTTERY_HEAP_SORT_NAME()
//#define pottery_heap_sort_heap POTTERY_HEAP_SORT_NAME(_heap)



// heap
#define POTTERY_HEAP_SORT_HEAP_NAME(name) POTTERY_HEAP_SORT_NAME(POTTERY_CONCAT(_heap, name))
//!!! AUTOGENERATED:heap/rename.t PREFIX:pottery_heap_sort_heap MACRO:POTTERY_HEAP_SORT_HEAP_NAME
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Renames insertion_sort identifiers with prefix "pottery_heap_sort_heap"
    // using macro POTTERY_HEAP_SORT_HEAP_NAME()
    #define pottery_heap_sort_heap_ref_t POTTERY_HEAP_SORT_HEAP_NAME(_ref_t)
    #define pottery_heap_sort_heap_value_t POTTERY_HEAP_SORT_HEAP_NAME(_value_t)
    #define pottery_heap_sort_heap_context_t POTTERY_HEAP_SORT_HEAP_NAME(_context_t)
    #define pottery_heap_sort_heap_state_t POTTERY_HEAP_SORT_HEAP_NAME(_state_t)

    #define pottery_heap_sort_heap POTTERY_HEAP_SORT_HEAP_NAME()
    #define pottery_heap_sort_heap_access POTTERY_HEAP_SORT_HEAP_NAME(_access)
    #define pottery_heap_sort_heap_set_index POTTERY_HEAP_SORT_HEAP_NAME(_set_index)

    #define pottery_heap_sort_heap_parent POTTERY_HEAP_SORT_HEAP_NAME(_parent)
    #define pottery_heap_sort_heap_child_left POTTERY_HEAP_SORT_HEAP_NAME(_child_left)
    #define pottery_heap_sort_heap_child_right POTTERY_HEAP_SORT_HEAP_NAME(_child_right)
    #define pottery_heap_sort_heap_sift_down POTTERY_HEAP_SORT_HEAP_NAME(_sift_down)
    #define pottery_heap_sort_heap_sift_up POTTERY_HEAP_SORT_HEAP_NAME(_sift_up)
    #define pottery_heap_sort_heap_build_impl POTTERY_HEAP_SORT_HEAP_NAME(_build_impl)
    #define pottery_heap_sort_heap_push_impl POTTERY_HEAP_SORT_HEAP_NAME(_push_impl)
    #define pottery_heap_sort_heap_pop_impl POTTERY_HEAP_SORT_HEAP_NAME(_pop_impl)
    #define pottery_heap_sort_heap_remove_impl POTTERY_HEAP_SORT_HEAP_NAME(_remove_impl)
    #define pottery_heap_sort_heap_valid_count_impl POTTERY_HEAP_SORT_HEAP_NAME(_valid_count_impl)
    #define pottery_heap_sort_heap_build POTTERY_HEAP_SORT_HEAP_NAME(_build)
    #define pottery_heap_sort_heap_push POTTERY_HEAP_SORT_HEAP_NAME(_push)
    #define pottery_heap_sort_heap_pop POTTERY_HEAP_SORT_HEAP_NAME(_pop)
    #define pottery_heap_sort_heap_remove POTTERY_HEAP_SORT_HEAP_NAME(_remove)
    #define pottery_heap_sort_heap_valid POTTERY_HEAP_SORT_HEAP_NAME(_valid)
    #define pottery_heap_sort_heap_valid_count POTTERY_HEAP_SORT_HEAP_NAME(_valid_count)
//!!! END_AUTOGENERATED
