/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_RING_IMPL
#error "This is an internal header. Do not include it."
#endif

#undef pottery_ring_t
#undef pottery_ring_value_t
#undef pottery_ring_entry_t
#undef pottery_ring_page_t

#undef pottery_ring_at
#undef pottery_ring_select
#undef pottery_ring_index
#undef pottery_ring_first
#undef pottery_ring_last
#undef pottery_ring_next
#undef pottery_ring_previous
#undef pottery_ring_begin
#undef pottery_ring_end
#undef pottery_ring_ref_exists

#undef pottery_ring_displace_all
#undef pottery_ring_remove_all
#undef pottery_ring_impl_destroy_all

#undef pottery_ring_init
#undef pottery_ring_destroy
#undef pottery_ring_count
#undef pottery_ring_is_empty
#undef pottery_ring_clear
#undef pottery_ring_emplace_first
#undef pottery_ring_emplace_last
#undef pottery_ring_insert_first
#undef pottery_ring_insert_last
#undef pottery_ring_insert
#undef pottery_ring_insert_first_bulk
#undef pottery_ring_insert_last_bulk
#undef pottery_ring_insert_bulk
#undef pottery_ring_displace_first
#undef pottery_ring_displace_last
#undef pottery_ring_remove_first
#undef pottery_ring_remove_last
#undef pottery_ring_extract_first
#undef pottery_ring_extract_last
#undef pottery_ring_extract
#undef pottery_ring_extract_first_bulk
#undef pottery_ring_extract_last_bulk
#undef pottery_ring_extract_bulk
#undef pottery_ring_emplace_first
#undef pottery_ring_emplace_last
#undef pottery_ring_emplace
#undef pottery_ring_access_first
#undef pottery_ring_access_last
#undef pottery_ring_access
#undef pottery_ring_drop_first
#undef pottery_ring_drop_last
#undef pottery_ring_drop

#undef pottery_ring_sanity_check
#undef pottery_ring_grow

#undef POTTERY_RING_PREFIX
#undef POTTERY_RING_VALUE_TYPE
#undef POTTERY_RING_EXTERN
#undef POTTERY_RING_EXTERNAL_ALLOC



// lifecycle

#undef POTTERY_RING_LIFECYCLE_PREFIX

//!!! AUTOGENERATED:lifecycle/unrename.m.h PREFIX:pottery_ring_lifecycle
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames lifecycle identifiers with prefix "pottery_ring_lifecycle"

    // types
    #undef pottery_ring_lifecycle_ref_t
    #undef pottery_ring_lifecycle_const_ref_t
    #undef pottery_ring_lifecycle_value_t
    #undef pottery_ring_lifecycle_context_t

    // fundamental operations
    #undef pottery_ring_lifecycle_init_steal
    #undef pottery_ring_lifecycle_init_copy
    #undef pottery_ring_lifecycle_init
    #undef pottery_ring_lifecycle_destroy
    #undef pottery_ring_lifecycle_swap
    #undef pottery_ring_lifecycle_move
    #undef pottery_ring_lifecycle_steal
    #undef pottery_ring_lifecycle_copy

    // bulk operations
    #undef pottery_ring_lifecycle_move_bulk
    #undef pottery_ring_lifecycle_move_bulk_restrict
    #undef pottery_ring_lifecycle_move_bulk_restrict_impl
    #undef pottery_ring_lifecycle_move_bulk_up
    #undef pottery_ring_lifecycle_move_bulk_up_impl
    #undef pottery_ring_lifecycle_move_bulk_down
    #undef pottery_ring_lifecycle_move_bulk_down_impl
    #undef pottery_ring_lifecycle_destroy_bulk
//!!! END_AUTOGENERATED



// alloc

#undef POTTERY_RING_ALLOC_PREFIX

//!!! AUTOGENERATED:alloc/unrename.m.h PREFIX:pottery_ring_alloc
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames alloc identifiers with prefix "pottery_ring_alloc"

    #undef pottery_ring_alloc_free
    #undef pottery_ring_alloc_impl_free_ea
    #undef pottery_ring_alloc_impl_free_fa

    #undef pottery_ring_alloc_malloc
    #undef pottery_ring_alloc_impl_malloc_ea
    #undef pottery_ring_alloc_impl_malloc_fa

    #undef pottery_ring_alloc_malloc_zero
    #undef pottery_ring_alloc_impl_malloc_zero_ea
    #undef pottery_ring_alloc_impl_malloc_zero_fa
    #undef pottery_ring_alloc_impl_malloc_zero_fa_wrap

    #undef pottery_ring_alloc_malloc_array_at_least
    #undef pottery_ring_alloc_impl_malloc_array_at_least_ea
    #undef pottery_ring_alloc_impl_malloc_array_at_least_fa

    #undef pottery_ring_alloc_malloc_array
    #undef pottery_ring_alloc_malloc_array_zero
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
