/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_ALLOC_INTERNAL
#error "This is an internal header. Do not include it."
#endif



/*
 * Configuration
 */

// user configuration

#undef POTTERY_ALLOC_PREFIX

// internal stuff

#undef POTTERY_ALLOC_EXTERN

//!!! AUTOGENERATED:alloc/unconfigure.m.h PREFIX:POTTERY_ALLOC
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) alloc configuration on POTTERY_ALLOC
    #undef POTTERY_ALLOC_CONTEXT_TYPE

    #undef POTTERY_ALLOC_FREE
    #undef POTTERY_ALLOC_MALLOC
    #undef POTTERY_ALLOC_ZALLOC
    #undef POTTERY_ALLOC_REALLOC
    #undef POTTERY_ALLOC_MALLOC_GOOD_SIZE

    #undef POTTERY_ALLOC_ALIGNED_FREE
    #undef POTTERY_ALLOC_ALIGNED_MALLOC
    #undef POTTERY_ALLOC_ALIGNED_ZALLOC
    #undef POTTERY_ALLOC_ALIGNED_REALLOC
    #undef POTTERY_ALLOC_ALIGNED_MALLOC_GOOD_SIZE
//!!! END_AUTOGENERATED


/*
 * Renaming
 */

//!!! AUTOGENERATED:alloc/unrename.m.h PREFIX:pottery_alloc
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames alloc identifiers with prefix "pottery_alloc"

    #undef pottery_alloc_free
    #undef pottery_alloc_impl_free_ea
    #undef pottery_alloc_impl_free_fa

    #undef pottery_alloc_malloc
    #undef pottery_alloc_impl_malloc_ea
    #undef pottery_alloc_impl_malloc_fa

    #undef pottery_alloc_malloc_zero
    #undef pottery_alloc_impl_malloc_zero_ea
    #undef pottery_alloc_impl_malloc_zero_fa
    #undef pottery_alloc_impl_malloc_zero_fa_wrap

    #undef pottery_alloc_malloc_array_at_least
    #undef pottery_alloc_impl_malloc_array_at_least_ea
    #undef pottery_alloc_impl_malloc_array_at_least_fa

    #undef pottery_alloc_malloc_array
    #undef pottery_alloc_malloc_array_zero
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
