/*
 * MIT License
 *
 * Copyright (c) 2020 Nicholas Fraser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_OPEN_HASH_MAP_IMPL
#error "This is an internal header. Do not include it."
#endif



/*
 * Forwarded configurations
 */

//!!! AUTOGENERATED:alloc/unconfigure.t PREFIX:POTTERY_OPEN_HASH_MAP_ALLOC
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Undefines (forwardable/forwarded) alloc configuration on POTTERY_OPEN_HASH_MAP_ALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_CONTEXT_TYPE

    #undef POTTERY_OPEN_HASH_MAP_ALLOC_FREE
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_MALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ZALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_REALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_MALLOC_EXPAND
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_MALLOC_USABLE_SIZE
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_MALLOC_GOOD_SIZE

    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_FREE
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_MALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_ZALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_REALLOC
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_MALLOC_EXPAND
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_MALLOC_USABLE_SIZE
    #undef POTTERY_OPEN_HASH_MAP_ALLOC_ALIGNED_MALLOC_GOOD_SIZE
//!!! END_AUTOGENERATED

//!!! AUTOGENERATED:open_hash_table/unconfigure.t PREFIX:POTTERY_OPEN_HASH_MAP
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.

    // Undefines (forwardable/forwarded) lifecycle configuration on POTTERY_OPEN_HASH_MAP

    #undef POTTERY_OPEN_HASH_MAP_VALUE_TYPE
    #undef POTTERY_OPEN_HASH_MAP_REF_TYPE
    #undef POTTERY_OPEN_HASH_MAP_KEY_TYPE

    #undef POTTERY_OPEN_HASH_MAP_KEY_HASH

    #undef POTTERY_OPEN_HASH_MAP_IS_EMPTY
    #undef POTTERY_OPEN_HASH_MAP_SET_EMPTY

    #undef POTTERY_OPEN_HASH_MAP_IS_TOMBSTONE
    #undef POTTERY_OPEN_HASH_MAP_SET_TOMBSTONE

    #undef POTTERY_OPEN_HASH_MAP_IS_ELEMENT

    #undef POTTERY_OPEN_HASH_MAP_LINEAR_PROBING
    #undef POTTERY_OPEN_HASH_MAP_QUADRATIC_PROBING
    #undef POTTERY_OPEN_HASH_MAP_DOUBLE_HASHING
//!!! END_AUTOGENERATED



/*
 * Configuration
 */

// internal

#undef POTTERY_OPEN_HASH_MAP_PREFIX
#undef POTTERY_OPEN_HASH_MAP_MINIMUM_CAPACITY
#undef POTTERY_OPEN_HASH_MAP_TYPEDEFS
#undef POTTERY_OPEN_HASH_MAP_NAME
#undef POTTERY_OPEN_HASH_MAP_DOUBLE_ENDED
#undef POTTERY_OPEN_HASH_MAP_ELEMENT_TYPE

#undef POTTERY_OPEN_HASH_MAP_INTERNAL_CAPACITY
#undef POTTERY_OPEN_HASH_MAP_EXTERN

#undef POTTERY_OPEN_HASH_MAP_CONTEXT_TYPE
#undef POTTERY_OPEN_HASH_MAP_CONTEXT_VAL


/*
 * Renaming
 */

#undef pottery_open_hash_map_data
#undef pottery_open_hash_map_const_data
#undef pottery_open_hash_map_capacity
#undef pottery_open_hash_map_minimum_capacity

#undef pottery_open_hash_map_insert_open_hash_map
#undef pottery_open_hash_map_insert_last_open_hash_map
#undef pottery_open_hash_map_insert_first_open_hash_map

#undef pottery_open_hash_map_impl_alloc
#undef pottery_open_hash_map_impl_alloc
#undef pottery_open_hash_map_impl_free
#undef pottery_open_hash_map_impl_create_space
#undef pottery_open_hash_map_impl_remove_space
#undef pottery_open_hash_map_impl_clear
#undef pottery_open_hash_map_impl_destroy_all
#undef pottery_open_hash_map_impl_copy
#undef pottery_open_hash_map_impl_reset



// dynamic array functions
//!!! AUTOGENERATED:array/unrename.t PREFIX:pottery_open_hash_map
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_open_hash_map"

    // types
    #undef pottery_open_hash_map_t
    #undef pottery_open_hash_map_element_t
    #undef pottery_open_hash_map_ref_t
    #undef pottery_open_hash_map_entry_t

    // fundamental operations
    #undef pottery_open_hash_map_copy
    #undef pottery_open_hash_map_destroy
    #undef pottery_open_hash_map_init
    #undef pottery_open_hash_map_init_copy
    #undef pottery_open_hash_map_init_steal
    #undef pottery_open_hash_map_move
    #undef pottery_open_hash_map_steal
    #undef pottery_open_hash_map_swap

    // entry operations
    #undef pottery_open_hash_map_entry_index
    #undef pottery_open_hash_map_entry_exists
    #undef pottery_open_hash_map_entry_equal
    #undef pottery_open_hash_map_entry_element

    // lookup
    #undef pottery_open_hash_map_count
    #undef pottery_open_hash_map_is_empty
    #undef pottery_open_hash_map_at
    #undef pottery_open_hash_map_index
    #undef pottery_open_hash_map_first
    #undef pottery_open_hash_map_last
    #undef pottery_open_hash_map_any

    // iteration
    #undef pottery_open_hash_map_begin
    #undef pottery_open_hash_map_end
    #undef pottery_open_hash_map_next
    #undef pottery_open_hash_map_previous

    // misc
    #undef pottery_open_hash_map_reserve
    #undef pottery_open_hash_map_shrink

    // insert
    #undef pottery_open_hash_map_insert_at
    #undef pottery_open_hash_map_insert_first
    #undef pottery_open_hash_map_insert_last
    #undef pottery_open_hash_map_insert_before
    #undef pottery_open_hash_map_insert_after
    #undef pottery_open_hash_map_insert_at_bulk
    #undef pottery_open_hash_map_insert_first_bulk
    #undef pottery_open_hash_map_insert_last_bulk
    #undef pottery_open_hash_map_insert_before_bulk
    #undef pottery_open_hash_map_insert_after_bulk

    // emplace
    #undef pottery_open_hash_map_emplace_at
    #undef pottery_open_hash_map_emplace_first
    #undef pottery_open_hash_map_emplace_last
    #undef pottery_open_hash_map_emplace_before
    #undef pottery_open_hash_map_emplace_after
    #undef pottery_open_hash_map_emplace_at_bulk
    #undef pottery_open_hash_map_emplace_first_bulk
    #undef pottery_open_hash_map_emplace_last_bulk
    #undef pottery_open_hash_map_emplace_before_bulk
    #undef pottery_open_hash_map_emplace_after_bulk

    // construct
    #undef pottery_open_hash_map_construct_at
    #undef pottery_open_hash_map_construct_first
    #undef pottery_open_hash_map_construct_last
    #undef pottery_open_hash_map_construct_before
    #undef pottery_open_hash_map_construct_after

    // extract
    #undef pottery_open_hash_map_extract
    #undef pottery_open_hash_map_extract_at
    #undef pottery_open_hash_map_extract_first
    #undef pottery_open_hash_map_extract_last
    #undef pottery_open_hash_map_extract_and_next
    #undef pottery_open_hash_map_extract_and_previous

    // remove
    #undef pottery_open_hash_map_remove
    #undef pottery_open_hash_map_remove_at
    #undef pottery_open_hash_map_remove_first
    #undef pottery_open_hash_map_remove_last
    #undef pottery_open_hash_map_remove_and_next
    #undef pottery_open_hash_map_remove_and_previous
    #undef pottery_open_hash_map_remove_all
    #undef pottery_open_hash_map_remove_at_bulk
    #undef pottery_open_hash_map_remove_first_bulk
    #undef pottery_open_hash_map_remove_last_bulk
    #undef pottery_open_hash_map_remove_at_bulk

    // displace
    #undef pottery_open_hash_map_displace
    #undef pottery_open_hash_map_displace_at
    #undef pottery_open_hash_map_displace_first
    #undef pottery_open_hash_map_displace_last
    #undef pottery_open_hash_map_displace_and_next
    #undef pottery_open_hash_map_displace_and_previous
    #undef pottery_open_hash_map_displace_all
    #undef pottery_open_hash_map_displace_at_bulk
    #undef pottery_open_hash_map_displace_first_bulk
    #undef pottery_open_hash_map_displace_last_bulk
//!!! END_AUTOGENERATED



// lifecycle

#undef POTTERY_OPEN_HASH_MAP_LIFECYCLE_PREFIX

//!!! AUTOGENERATED:lifecycle/unrename.t PREFIX:pottery_open_hash_map_element
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames lifecycle identifiers with prefix "pottery_open_hash_map_element"

    // types
    #undef pottery_open_hash_map_element_ref_t
    #undef pottery_open_hash_map_element_const_ref_t
    #undef pottery_open_hash_map_element_value_t
    #undef pottery_open_hash_map_element_context_t

    // fundamental operations
    #undef pottery_open_hash_map_element_init_steal
    #undef pottery_open_hash_map_element_init_copy
    #undef pottery_open_hash_map_element_init
    #undef pottery_open_hash_map_element_destroy
    #undef pottery_open_hash_map_element_swap
    #undef pottery_open_hash_map_element_move
    #undef pottery_open_hash_map_element_steal
    #undef pottery_open_hash_map_element_copy

    // bulk operations
    #undef pottery_open_hash_map_element_move_bulk
    #undef pottery_open_hash_map_element_move_bulk_restrict
    #undef pottery_open_hash_map_element_move_bulk_restrict_impl
    #undef pottery_open_hash_map_element_move_bulk_up
    #undef pottery_open_hash_map_element_move_bulk_up_impl
    #undef pottery_open_hash_map_element_move_bulk_down
    #undef pottery_open_hash_map_element_move_bulk_down_impl
    #undef pottery_open_hash_map_element_destroy_bulk

    // C++
    #undef pottery_open_hash_map_element_construct
    #undef pottery_open_hash_map_element_assign
//!!! END_AUTOGENERATED



// alloc

#undef POTTERY_OPEN_HASH_MAP_ALLOC_PREFIX

//!!! AUTOGENERATED:alloc/unrename.t PREFIX:pottery_open_hash_map_alloc
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames alloc identifiers with prefix "pottery_open_hash_map_alloc"

    #undef pottery_open_hash_map_alloc_free
    #undef pottery_open_hash_map_alloc_impl_free_ea
    #undef pottery_open_hash_map_alloc_impl_free_fa

    #undef pottery_open_hash_map_alloc_malloc
    #undef pottery_open_hash_map_alloc_impl_malloc_ea
    #undef pottery_open_hash_map_alloc_impl_malloc_fa

    #undef pottery_open_hash_map_alloc_malloc_zero
    #undef pottery_open_hash_map_alloc_impl_malloc_zero_ea
    #undef pottery_open_hash_map_alloc_impl_malloc_zero_fa
    #undef pottery_open_hash_map_alloc_impl_malloc_zero_fa_wrap

    #undef pottery_open_hash_map_alloc_malloc_array_at_least
    #undef pottery_open_hash_map_alloc_impl_malloc_array_at_least_ea
    #undef pottery_open_hash_map_alloc_impl_malloc_array_at_least_fa

    #undef pottery_open_hash_map_alloc_malloc_array
    #undef pottery_open_hash_map_alloc_malloc_array_zero
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
