/*
 * MIT License
 *
 * Copyright (c) 2020-2021 11037650 Canada Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef POTTERY_DEQUE_IMPL
#error "This is an internal header. Do not include it."
#endif

#undef POTTERY_DEQUE_NAME
#undef POTTERY_DEQUE_PREFIX
#undef POTTERY_DEQUE_VALUE_TYPE
#undef POTTERY_DEQUE_EXTERN

// public deque-specific functions
#undef pottery_deque_next_bulk
#undef pottery_deque_previous_bulk

// internal types and functions
#undef pottery_deque_page_t
#undef pottery_deque_ref_make
#undef pottery_deque_per_page
#undef pottery_deque_sanity_check
#undef pottery_deque_acquire_page
#undef pottery_deque_release_page
#undef pottery_deque_destroy_all
#undef pottery_deque_set_clear

// common array types and functions
//!!! AUTOGENERATED:array/unrename.m.h PREFIX:pottery_deque
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_deque"

    // types
    #undef pottery_deque_t
    #undef pottery_deque_value_t
    #undef pottery_deque_ref_t
    #undef pottery_deque_entry_t
    #undef pottery_deque_context_t

    // fundamental operations
    #undef pottery_deque_copy
    #undef pottery_deque_destroy
    #undef pottery_deque_init
    #undef pottery_deque_init_copy
    #undef pottery_deque_init_steal
    #undef pottery_deque_move
    #undef pottery_deque_steal
    #undef pottery_deque_swap

    // entry operations
    #undef pottery_deque_entry_exists
    #undef pottery_deque_entry_equal
    #undef pottery_deque_entry_value

    // lookup
    #undef pottery_deque_count
    #undef pottery_deque_is_empty
    #undef pottery_deque_at
    #undef pottery_deque_first
    #undef pottery_deque_last
    #undef pottery_deque_any

    // iteration
    #undef pottery_deque_select
    #undef pottery_deque_index
    #undef pottery_deque_begin
    #undef pottery_deque_end
    #undef pottery_deque_next
    #undef pottery_deque_previous

    // misc
    #undef pottery_deque_reserve
    #undef pottery_deque_shrink

    // insert
    #undef pottery_deque_insert_at
    #undef pottery_deque_insert_first
    #undef pottery_deque_insert_last
    #undef pottery_deque_insert_before
    #undef pottery_deque_insert_after
    #undef pottery_deque_insert_at_bulk
    #undef pottery_deque_insert_first_bulk
    #undef pottery_deque_insert_last_bulk
    #undef pottery_deque_insert_before_bulk
    #undef pottery_deque_insert_after_bulk

    // emplace
    #undef pottery_deque_emplace_at
    #undef pottery_deque_emplace_first
    #undef pottery_deque_emplace_last
    #undef pottery_deque_emplace_before
    #undef pottery_deque_emplace_after
    #undef pottery_deque_emplace_at_bulk
    #undef pottery_deque_emplace_first_bulk
    #undef pottery_deque_emplace_last_bulk
    #undef pottery_deque_emplace_before_bulk
    #undef pottery_deque_emplace_after_bulk

    // construct
    #undef pottery_deque_construct_at
    #undef pottery_deque_construct_first
    #undef pottery_deque_construct_last
    #undef pottery_deque_construct_before
    #undef pottery_deque_construct_after

    // extract
    #undef pottery_deque_extract
    #undef pottery_deque_extract_at
    #undef pottery_deque_extract_first
    #undef pottery_deque_extract_last
    #undef pottery_deque_extract_and_next
    #undef pottery_deque_extract_and_previous

    // remove
    #undef pottery_deque_remove
    #undef pottery_deque_remove_at
    #undef pottery_deque_remove_first
    #undef pottery_deque_remove_last
    #undef pottery_deque_remove_and_next
    #undef pottery_deque_remove_and_previous
    #undef pottery_deque_remove_all
    #undef pottery_deque_remove_at_bulk
    #undef pottery_deque_remove_first_bulk
    #undef pottery_deque_remove_last_bulk
    #undef pottery_deque_remove_at_bulk

    // displace
    #undef pottery_deque_displace
    #undef pottery_deque_displace_at
    #undef pottery_deque_displace_first
    #undef pottery_deque_displace_last
    #undef pottery_deque_displace_and_next
    #undef pottery_deque_displace_and_previous
    #undef pottery_deque_displace_all
    #undef pottery_deque_displace_at_bulk
    #undef pottery_deque_displace_first_bulk
    #undef pottery_deque_displace_last_bulk
//!!! END_AUTOGENERATED


// ring
#undef pottery_deque_page_ring_t

//!!! AUTOGENERATED:array/unrename.m.h PREFIX:pottery_deque_page_ring
    // This block is auto-generated. Do not modify until END_AUTOGENERATED.
    // Un-renames array identifiers with prefix "pottery_deque_page_ring"

    // types
    #undef pottery_deque_page_ring_t
    #undef pottery_deque_page_ring_value_t
    #undef pottery_deque_page_ring_ref_t
    #undef pottery_deque_page_ring_entry_t
    #undef pottery_deque_page_ring_context_t

    // fundamental operations
    #undef pottery_deque_page_ring_copy
    #undef pottery_deque_page_ring_destroy
    #undef pottery_deque_page_ring_init
    #undef pottery_deque_page_ring_init_copy
    #undef pottery_deque_page_ring_init_steal
    #undef pottery_deque_page_ring_move
    #undef pottery_deque_page_ring_steal
    #undef pottery_deque_page_ring_swap

    // entry operations
    #undef pottery_deque_page_ring_entry_exists
    #undef pottery_deque_page_ring_entry_equal
    #undef pottery_deque_page_ring_entry_value

    // lookup
    #undef pottery_deque_page_ring_count
    #undef pottery_deque_page_ring_is_empty
    #undef pottery_deque_page_ring_at
    #undef pottery_deque_page_ring_first
    #undef pottery_deque_page_ring_last
    #undef pottery_deque_page_ring_any

    // iteration
    #undef pottery_deque_page_ring_select
    #undef pottery_deque_page_ring_index
    #undef pottery_deque_page_ring_begin
    #undef pottery_deque_page_ring_end
    #undef pottery_deque_page_ring_next
    #undef pottery_deque_page_ring_previous

    // misc
    #undef pottery_deque_page_ring_reserve
    #undef pottery_deque_page_ring_shrink

    // insert
    #undef pottery_deque_page_ring_insert_at
    #undef pottery_deque_page_ring_insert_first
    #undef pottery_deque_page_ring_insert_last
    #undef pottery_deque_page_ring_insert_before
    #undef pottery_deque_page_ring_insert_after
    #undef pottery_deque_page_ring_insert_at_bulk
    #undef pottery_deque_page_ring_insert_first_bulk
    #undef pottery_deque_page_ring_insert_last_bulk
    #undef pottery_deque_page_ring_insert_before_bulk
    #undef pottery_deque_page_ring_insert_after_bulk

    // emplace
    #undef pottery_deque_page_ring_emplace_at
    #undef pottery_deque_page_ring_emplace_first
    #undef pottery_deque_page_ring_emplace_last
    #undef pottery_deque_page_ring_emplace_before
    #undef pottery_deque_page_ring_emplace_after
    #undef pottery_deque_page_ring_emplace_at_bulk
    #undef pottery_deque_page_ring_emplace_first_bulk
    #undef pottery_deque_page_ring_emplace_last_bulk
    #undef pottery_deque_page_ring_emplace_before_bulk
    #undef pottery_deque_page_ring_emplace_after_bulk

    // construct
    #undef pottery_deque_page_ring_construct_at
    #undef pottery_deque_page_ring_construct_first
    #undef pottery_deque_page_ring_construct_last
    #undef pottery_deque_page_ring_construct_before
    #undef pottery_deque_page_ring_construct_after

    // extract
    #undef pottery_deque_page_ring_extract
    #undef pottery_deque_page_ring_extract_at
    #undef pottery_deque_page_ring_extract_first
    #undef pottery_deque_page_ring_extract_last
    #undef pottery_deque_page_ring_extract_and_next
    #undef pottery_deque_page_ring_extract_and_previous

    // remove
    #undef pottery_deque_page_ring_remove
    #undef pottery_deque_page_ring_remove_at
    #undef pottery_deque_page_ring_remove_first
    #undef pottery_deque_page_ring_remove_last
    #undef pottery_deque_page_ring_remove_and_next
    #undef pottery_deque_page_ring_remove_and_previous
    #undef pottery_deque_page_ring_remove_all
    #undef pottery_deque_page_ring_remove_at_bulk
    #undef pottery_deque_page_ring_remove_first_bulk
    #undef pottery_deque_page_ring_remove_last_bulk
    #undef pottery_deque_page_ring_remove_at_bulk

    // displace
    #undef pottery_deque_page_ring_displace
    #undef pottery_deque_page_ring_displace_at
    #undef pottery_deque_page_ring_displace_first
    #undef pottery_deque_page_ring_displace_last
    #undef pottery_deque_page_ring_displace_and_next
    #undef pottery_deque_page_ring_displace_and_previous
    #undef pottery_deque_page_ring_displace_all
    #undef pottery_deque_page_ring_displace_at_bulk
    #undef pottery_deque_page_ring_displace_first_bulk
    #undef pottery_deque_page_ring_displace_last_bulk
//!!! END_AUTOGENERATED



#include "pottery/platform/pottery_platform_pragma_pop.t.h"
